# coding: utf-8

"""
    Pago API

    Personal finance tracking API. All /api/* endpoints require either a session cookie (browser) or an Authorization: Bearer <token> header (machine clients).

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from pago_sdk.models.web_monthly_analytics_response import WebMonthlyAnalyticsResponse

class TestWebMonthlyAnalyticsResponse(unittest.TestCase):
    """WebMonthlyAnalyticsResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> WebMonthlyAnalyticsResponse:
        """Test WebMonthlyAnalyticsResponse
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `WebMonthlyAnalyticsResponse`
        """
        model = WebMonthlyAnalyticsResponse()
        if include_optional:
            return WebMonthlyAnalyticsResponse(
                balance = 1.337,
                by_category = pago_sdk.models.web/category_breakdown.web.CategoryBreakdown(
                    expense = [
                        pago_sdk.models.web/category_entry.web.CategoryEntry(
                            amount = 1.337, 
                            category = '', 
                            count = 56, 
                            pct = 1.337, )
                        ], 
                    income = [
                        pago_sdk.models.web/category_entry.web.CategoryEntry(
                            amount = 1.337, 
                            category = '', 
                            count = 56, 
                            pct = 1.337, )
                        ], ),
                month = '',
                total_expenses = 1.337,
                total_income = 1.337
            )
        else:
            return WebMonthlyAnalyticsResponse(
        )
        """

    def testWebMonthlyAnalyticsResponse(self):
        """Test WebMonthlyAnalyticsResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
