# coding: utf-8

"""
    Pago API

    Personal finance tracking API. All /api/* endpoints require either a session cookie (browser) or an Authorization: Bearer <token> header (machine clients).

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from pago_sdk.models.web_search_transactions_response import WebSearchTransactionsResponse

class TestWebSearchTransactionsResponse(unittest.TestCase):
    """WebSearchTransactionsResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> WebSearchTransactionsResponse:
        """Test WebSearchTransactionsResponse
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `WebSearchTransactionsResponse`
        """
        model = WebSearchTransactionsResponse()
        if include_optional:
            return WebSearchTransactionsResponse(
                limit = 56,
                offset = 56,
                total = 56,
                transactions = [
                    pago_sdk.models.web/transaction_dto.web.TransactionDTO(
                        amount = 1.337, 
                        category = '', 
                        date = '', 
                        description = '', 
                        id = 56, 
                        type = '', )
                    ]
            )
        else:
            return WebSearchTransactionsResponse(
        )
        """

    def testWebSearchTransactionsResponse(self):
        """Test WebSearchTransactionsResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
