# coding: utf-8

"""
    Pago API

    Personal finance tracking API. All /api/* endpoints require either a session cookie (browser) or an Authorization: Bearer <token> header (machine clients).

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from pago_sdk.models.web_stats_response import WebStatsResponse

class TestWebStatsResponse(unittest.TestCase):
    """WebStatsResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> WebStatsResponse:
        """Test WebStatsResponse
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `WebStatsResponse`
        """
        model = WebStatsResponse()
        if include_optional:
            return WebStatsResponse(
                balance = 1.337,
                total_expenses = 1.337,
                total_income = 1.337,
                total_transactions = 56
            )
        else:
            return WebStatsResponse(
        )
        """

    def testWebStatsResponse(self):
        """Test WebStatsResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
