# coding: utf-8

"""
    Pago API

    Personal finance tracking API. All /api/* endpoints require either a session cookie (browser) or an Authorization: Bearer <token> header (machine clients).

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from pago_sdk.models.web_trend_response import WebTrendResponse

class TestWebTrendResponse(unittest.TestCase):
    """WebTrendResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> WebTrendResponse:
        """Test WebTrendResponse
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `WebTrendResponse`
        """
        model = WebTrendResponse()
        if include_optional:
            return WebTrendResponse(
                var_from = '',
                points = [
                    pago_sdk.models.web/month_point.web.MonthPoint(
                        balance = 1.337, 
                        expense = 1.337, 
                        income = 1.337, 
                        month = '', )
                    ],
                to = ''
            )
        else:
            return WebTrendResponse(
        )
        """

    def testWebTrendResponse(self):
        """Test WebTrendResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
