# coding: utf-8

"""
    Pago API

    Personal finance tracking API. All /api/* endpoints require either a session cookie (browser) or an Authorization: Bearer <token> header (machine clients).

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from pago_sdk.api.budget_api import BudgetApi


class TestBudgetApi(unittest.TestCase):
    """BudgetApi unit test stubs"""

    def setUp(self) -> None:
        self.api = BudgetApi()

    def tearDown(self) -> None:
        pass

    def test_api_budget_delete(self) -> None:
        """Test case for api_budget_delete

        Delete the monthly budget
        """
        pass

    def test_api_budget_delete_0(self) -> None:
        """Test case for api_budget_delete_0

        Delete the monthly budget
        """
        pass

    def test_api_budget_delete_1(self) -> None:
        """Test case for api_budget_delete_1

        Delete the monthly budget
        """
        pass

    def test_api_budget_delete_2(self) -> None:
        """Test case for api_budget_delete_2

        Delete the monthly budget
        """
        pass

    def test_api_budget_get(self) -> None:
        """Test case for api_budget_get

        Delete the monthly budget
        """
        pass

    def test_api_budget_get_0(self) -> None:
        """Test case for api_budget_get_0

        Delete the monthly budget
        """
        pass

    def test_api_budget_get_1(self) -> None:
        """Test case for api_budget_get_1

        Delete the monthly budget
        """
        pass

    def test_api_budget_get_2(self) -> None:
        """Test case for api_budget_get_2

        Delete the monthly budget
        """
        pass

    def test_api_budget_post(self) -> None:
        """Test case for api_budget_post

        Delete the monthly budget
        """
        pass

    def test_api_budget_post_0(self) -> None:
        """Test case for api_budget_post_0

        Delete the monthly budget
        """
        pass

    def test_api_budget_post_1(self) -> None:
        """Test case for api_budget_post_1

        Delete the monthly budget
        """
        pass

    def test_api_budget_post_2(self) -> None:
        """Test case for api_budget_post_2

        Delete the monthly budget
        """
        pass

    def test_api_budget_put(self) -> None:
        """Test case for api_budget_put

        Delete the monthly budget
        """
        pass

    def test_api_budget_put_0(self) -> None:
        """Test case for api_budget_put_0

        Delete the monthly budget
        """
        pass

    def test_api_budget_put_1(self) -> None:
        """Test case for api_budget_put_1

        Delete the monthly budget
        """
        pass

    def test_api_budget_put_2(self) -> None:
        """Test case for api_budget_put_2

        Delete the monthly budget
        """
        pass


if __name__ == '__main__':
    unittest.main()
