# coding: utf-8

"""
    Pago API

    Personal finance tracking API. All /api/* endpoints require either a session cookie (browser) or an Authorization: Bearer <token> header (machine clients).

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from pago_sdk.api.transactions_api import TransactionsApi


class TestTransactionsApi(unittest.TestCase):
    """TransactionsApi unit test stubs"""

    def setUp(self) -> None:
        self.api = TransactionsApi()

    def tearDown(self) -> None:
        pass

    def test_api_categories_get(self) -> None:
        """Test case for api_categories_get

        List categories
        """
        pass

    def test_api_stats_get(self) -> None:
        """Test case for api_stats_get

        Monthly stats
        """
        pass

    def test_api_transactions_create_post(self) -> None:
        """Test case for api_transactions_create_post

        Create transaction
        """
        pass

    def test_api_transactions_delete_delete(self) -> None:
        """Test case for api_transactions_delete_delete

        Delete transaction
        """
        pass

    def test_api_transactions_get(self) -> None:
        """Test case for api_transactions_get

        List transactions for a month
        """
        pass


if __name__ == '__main__':
    unittest.main()
