# coding: utf-8

"""
    Pago API

    Personal finance tracking API. All /api/* endpoints require either a session cookie (browser) or an Authorization: Bearer <token> header (machine clients).

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from pago_sdk.models.web_create_transaction_request import WebCreateTransactionRequest

class TestWebCreateTransactionRequest(unittest.TestCase):
    """WebCreateTransactionRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> WebCreateTransactionRequest:
        """Test WebCreateTransactionRequest
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `WebCreateTransactionRequest`
        """
        model = WebCreateTransactionRequest()
        if include_optional:
            return WebCreateTransactionRequest(
                amount = 12.5,
                category = 'Food',
                var_date = '2026-05-21',
                description = 'lunch',
                type = 'Expense'
            )
        else:
            return WebCreateTransactionRequest(
        )
        """

    def testWebCreateTransactionRequest(self):
        """Test WebCreateTransactionRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
