# coding: utf-8

"""
    Pago API

    Personal finance tracking API. All /api/* endpoints require either a session cookie (browser) or an Authorization: Bearer <token> header (machine clients).

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from pago_sdk.models.web_edit_transaction_request import WebEditTransactionRequest

class TestWebEditTransactionRequest(unittest.TestCase):
    """WebEditTransactionRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> WebEditTransactionRequest:
        """Test WebEditTransactionRequest
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `WebEditTransactionRequest`
        """
        model = WebEditTransactionRequest()
        if include_optional:
            return WebEditTransactionRequest(
                amount = 19.9,
                category = 'Grocery',
                var_date = '2026-05-21',
                description = 'weekly shop',
                id = 42
            )
        else:
            return WebEditTransactionRequest(
        )
        """

    def testWebEditTransactionRequest(self):
        """Test WebEditTransactionRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
