# coding: utf-8

"""
    Pago API

    Personal finance tracking API. All /api/* endpoints require either a session cookie (browser) or an Authorization: Bearer <token> header (machine clients).

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from pago_sdk.api.analytics_api import AnalyticsApi


class TestAnalyticsApi(unittest.TestCase):
    """AnalyticsApi unit test stubs"""

    def setUp(self) -> None:
        self.api = AnalyticsApi()

    def tearDown(self) -> None:
        pass

    def test_api_analytics_monthly_get(self) -> None:
        """Test case for api_analytics_monthly_get

        Monthly category breakdown
        """
        pass

    def test_api_analytics_trend_get(self) -> None:
        """Test case for api_analytics_trend_get

        Monthly trend over the trailing N months
        """
        pass

    def test_api_analytics_year_get(self) -> None:
        """Test case for api_analytics_year_get

        Annual breakdown by month and category
        """
        pass


if __name__ == '__main__':
    unittest.main()
