/* tslint:disable */
/* eslint-disable */
/**
 * Pago API
 * Personal finance tracking API. All /api/_* endpoints require either a session cookie (browser) or an Authorization: Bearer <token> header (machine clients).
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface WebBudgetResponse
 */
export interface WebBudgetResponse {
    /**
     * 
     * @type {number}
     * @memberof WebBudgetResponse
     */
    amount?: number;
    /**
     * 
     * @type {string}
     * @memberof WebBudgetResponse
     */
    currency?: string;
    /**
     * 
     * @type {boolean}
     * @memberof WebBudgetResponse
     */
    hasBudget?: boolean;
    /**
     * 
     * @type {string}
     * @memberof WebBudgetResponse
     */
    month?: string;
    /**
     * 
     * @type {number}
     * @memberof WebBudgetResponse
     */
    pct?: number;
    /**
     * 
     * @type {number}
     * @memberof WebBudgetResponse
     */
    spent?: number;
}

/**
 * Check if a given object implements the WebBudgetResponse interface.
 */
export function instanceOfWebBudgetResponse(value: object): value is WebBudgetResponse {
    return true;
}

export function WebBudgetResponseFromJSON(json: any): WebBudgetResponse {
    return WebBudgetResponseFromJSONTyped(json, false);
}

export function WebBudgetResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): WebBudgetResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'amount': json['amount'] == null ? undefined : json['amount'],
        'currency': json['currency'] == null ? undefined : json['currency'],
        'hasBudget': json['hasBudget'] == null ? undefined : json['hasBudget'],
        'month': json['month'] == null ? undefined : json['month'],
        'pct': json['pct'] == null ? undefined : json['pct'],
        'spent': json['spent'] == null ? undefined : json['spent'],
    };
}

export function WebBudgetResponseToJSON(json: any): WebBudgetResponse {
    return WebBudgetResponseToJSONTyped(json, false);
}

export function WebBudgetResponseToJSONTyped(value?: WebBudgetResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'amount': value['amount'],
        'currency': value['currency'],
        'hasBudget': value['hasBudget'],
        'month': value['month'],
        'pct': value['pct'],
        'spent': value['spent'],
    };
}

