/* tslint:disable */
/* eslint-disable */
/**
 * Pago API
 * Personal finance tracking API. All /api/_* endpoints require either a session cookie (browser) or an Authorization: Bearer <token> header (machine clients).
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface WebBudgetUpsertRequest
 */
export interface WebBudgetUpsertRequest {
    /**
     * 
     * @type {number}
     * @memberof WebBudgetUpsertRequest
     */
    amount?: number;
}

/**
 * Check if a given object implements the WebBudgetUpsertRequest interface.
 */
export function instanceOfWebBudgetUpsertRequest(value: object): value is WebBudgetUpsertRequest {
    return true;
}

export function WebBudgetUpsertRequestFromJSON(json: any): WebBudgetUpsertRequest {
    return WebBudgetUpsertRequestFromJSONTyped(json, false);
}

export function WebBudgetUpsertRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): WebBudgetUpsertRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'amount': json['amount'] == null ? undefined : json['amount'],
    };
}

export function WebBudgetUpsertRequestToJSON(json: any): WebBudgetUpsertRequest {
    return WebBudgetUpsertRequestToJSONTyped(json, false);
}

export function WebBudgetUpsertRequestToJSONTyped(value?: WebBudgetUpsertRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'amount': value['amount'],
    };
}

