/* tslint:disable */
/* eslint-disable */
/**
 * Pago API
 * Personal finance tracking API. All /api/_* endpoints require either a session cookie (browser) or an Authorization: Bearer <token> header (machine clients).
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { WebCategoryEntry } from './WebCategoryEntry';
import {
    WebCategoryEntryFromJSON,
    WebCategoryEntryFromJSONTyped,
    WebCategoryEntryToJSON,
    WebCategoryEntryToJSONTyped,
} from './WebCategoryEntry';

/**
 * 
 * @export
 * @interface WebCategoryBreakdown
 */
export interface WebCategoryBreakdown {
    /**
     * 
     * @type {Array<WebCategoryEntry>}
     * @memberof WebCategoryBreakdown
     */
    expense?: Array<WebCategoryEntry>;
    /**
     * 
     * @type {Array<WebCategoryEntry>}
     * @memberof WebCategoryBreakdown
     */
    income?: Array<WebCategoryEntry>;
}

/**
 * Check if a given object implements the WebCategoryBreakdown interface.
 */
export function instanceOfWebCategoryBreakdown(value: object): value is WebCategoryBreakdown {
    return true;
}

export function WebCategoryBreakdownFromJSON(json: any): WebCategoryBreakdown {
    return WebCategoryBreakdownFromJSONTyped(json, false);
}

export function WebCategoryBreakdownFromJSONTyped(json: any, ignoreDiscriminator: boolean): WebCategoryBreakdown {
    if (json == null) {
        return json;
    }
    return {
        
        'expense': json['Expense'] == null ? undefined : ((json['Expense'] as Array<any>).map(WebCategoryEntryFromJSON)),
        'income': json['Income'] == null ? undefined : ((json['Income'] as Array<any>).map(WebCategoryEntryFromJSON)),
    };
}

export function WebCategoryBreakdownToJSON(json: any): WebCategoryBreakdown {
    return WebCategoryBreakdownToJSONTyped(json, false);
}

export function WebCategoryBreakdownToJSONTyped(value?: WebCategoryBreakdown | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'Expense': value['expense'] == null ? undefined : ((value['expense'] as Array<any>).map(WebCategoryEntryToJSON)),
        'Income': value['income'] == null ? undefined : ((value['income'] as Array<any>).map(WebCategoryEntryToJSON)),
    };
}

