/* tslint:disable */
/* eslint-disable */
/**
 * Pago API
 * Personal finance tracking API. All /api/_* endpoints require either a session cookie (browser) or an Authorization: Bearer <token> header (machine clients).
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface WebCategoryEntry
 */
export interface WebCategoryEntry {
    /**
     * 
     * @type {number}
     * @memberof WebCategoryEntry
     */
    amount?: number;
    /**
     * 
     * @type {string}
     * @memberof WebCategoryEntry
     */
    category?: string;
    /**
     * 
     * @type {number}
     * @memberof WebCategoryEntry
     */
    count?: number;
    /**
     * 
     * @type {number}
     * @memberof WebCategoryEntry
     */
    pct?: number;
}

/**
 * Check if a given object implements the WebCategoryEntry interface.
 */
export function instanceOfWebCategoryEntry(value: object): value is WebCategoryEntry {
    return true;
}

export function WebCategoryEntryFromJSON(json: any): WebCategoryEntry {
    return WebCategoryEntryFromJSONTyped(json, false);
}

export function WebCategoryEntryFromJSONTyped(json: any, ignoreDiscriminator: boolean): WebCategoryEntry {
    if (json == null) {
        return json;
    }
    return {
        
        'amount': json['amount'] == null ? undefined : json['amount'],
        'category': json['category'] == null ? undefined : json['category'],
        'count': json['count'] == null ? undefined : json['count'],
        'pct': json['pct'] == null ? undefined : json['pct'],
    };
}

export function WebCategoryEntryToJSON(json: any): WebCategoryEntry {
    return WebCategoryEntryToJSONTyped(json, false);
}

export function WebCategoryEntryToJSONTyped(value?: WebCategoryEntry | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'amount': value['amount'],
        'category': value['category'],
        'count': value['count'],
        'pct': value['pct'],
    };
}

