/* tslint:disable */
/* eslint-disable */
/**
 * Pago API
 * Personal finance tracking API. All /api/_* endpoints require either a session cookie (browser) or an Authorization: Bearer <token> header (machine clients).
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface WebCloneTransactionRequest
 */
export interface WebCloneTransactionRequest {
    /**
     * 
     * @type {number}
     * @memberof WebCloneTransactionRequest
     */
    id?: number;
}

/**
 * Check if a given object implements the WebCloneTransactionRequest interface.
 */
export function instanceOfWebCloneTransactionRequest(value: object): value is WebCloneTransactionRequest {
    return true;
}

export function WebCloneTransactionRequestFromJSON(json: any): WebCloneTransactionRequest {
    return WebCloneTransactionRequestFromJSONTyped(json, false);
}

export function WebCloneTransactionRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): WebCloneTransactionRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
    };
}

export function WebCloneTransactionRequestToJSON(json: any): WebCloneTransactionRequest {
    return WebCloneTransactionRequestToJSONTyped(json, false);
}

export function WebCloneTransactionRequestToJSONTyped(value?: WebCloneTransactionRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
    };
}

