/* tslint:disable */
/* eslint-disable */
/**
 * Pago API
 * Personal finance tracking API. All /api/_* endpoints require either a session cookie (browser) or an Authorization: Bearer <token> header (machine clients).
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface WebCreateTransactionRequest
 */
export interface WebCreateTransactionRequest {
    /**
     * 
     * @type {number}
     * @memberof WebCreateTransactionRequest
     */
    amount?: number;
    /**
     * 
     * @type {string}
     * @memberof WebCreateTransactionRequest
     */
    category?: string;
    /**
     * 
     * @type {string}
     * @memberof WebCreateTransactionRequest
     */
    date?: string;
    /**
     * 
     * @type {string}
     * @memberof WebCreateTransactionRequest
     */
    description?: string;
    /**
     * 
     * @type {string}
     * @memberof WebCreateTransactionRequest
     */
    type?: string;
}

/**
 * Check if a given object implements the WebCreateTransactionRequest interface.
 */
export function instanceOfWebCreateTransactionRequest(value: object): value is WebCreateTransactionRequest {
    return true;
}

export function WebCreateTransactionRequestFromJSON(json: any): WebCreateTransactionRequest {
    return WebCreateTransactionRequestFromJSONTyped(json, false);
}

export function WebCreateTransactionRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): WebCreateTransactionRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'amount': json['amount'] == null ? undefined : json['amount'],
        'category': json['category'] == null ? undefined : json['category'],
        'date': json['date'] == null ? undefined : json['date'],
        'description': json['description'] == null ? undefined : json['description'],
        'type': json['type'] == null ? undefined : json['type'],
    };
}

export function WebCreateTransactionRequestToJSON(json: any): WebCreateTransactionRequest {
    return WebCreateTransactionRequestToJSONTyped(json, false);
}

export function WebCreateTransactionRequestToJSONTyped(value?: WebCreateTransactionRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'amount': value['amount'],
        'category': value['category'],
        'date': value['date'],
        'description': value['description'],
        'type': value['type'],
    };
}

