/* tslint:disable */
/* eslint-disable */
/**
 * Pago API
 * Personal finance tracking API. All /api/_* endpoints require either a session cookie (browser) or an Authorization: Bearer <token> header (machine clients).
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface WebCategoriesResponse
 */
export interface WebCategoriesResponse {
    /**
     * 
     * @type {Array<string>}
     * @memberof WebCategoriesResponse
     */
    categories?: Array<string>;
}

/**
 * Check if a given object implements the WebCategoriesResponse interface.
 */
export function instanceOfWebCategoriesResponse(value: object): value is WebCategoriesResponse {
    return true;
}

export function WebCategoriesResponseFromJSON(json: any): WebCategoriesResponse {
    return WebCategoriesResponseFromJSONTyped(json, false);
}

export function WebCategoriesResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): WebCategoriesResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'categories': json['categories'] == null ? undefined : json['categories'],
    };
}

export function WebCategoriesResponseToJSON(json: any): WebCategoriesResponse {
    return WebCategoriesResponseToJSONTyped(json, false);
}

export function WebCategoriesResponseToJSONTyped(value?: WebCategoriesResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'categories': value['categories'],
    };
}

