/* tslint:disable */
/* eslint-disable */
/**
 * Pago API
 * Personal finance tracking API. All /api/_* endpoints require either a session cookie (browser) or an Authorization: Bearer <token> header (machine clients).
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface WebDeleteTransactionRequest
 */
export interface WebDeleteTransactionRequest {
    /**
     * 
     * @type {number}
     * @memberof WebDeleteTransactionRequest
     */
    id?: number;
}

/**
 * Check if a given object implements the WebDeleteTransactionRequest interface.
 */
export function instanceOfWebDeleteTransactionRequest(value: object): value is WebDeleteTransactionRequest {
    return true;
}

export function WebDeleteTransactionRequestFromJSON(json: any): WebDeleteTransactionRequest {
    return WebDeleteTransactionRequestFromJSONTyped(json, false);
}

export function WebDeleteTransactionRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): WebDeleteTransactionRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
    };
}

export function WebDeleteTransactionRequestToJSON(json: any): WebDeleteTransactionRequest {
    return WebDeleteTransactionRequestToJSONTyped(json, false);
}

export function WebDeleteTransactionRequestToJSONTyped(value?: WebDeleteTransactionRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
    };
}

