/* tslint:disable */
/* eslint-disable */
/**
 * Pago API
 * Personal finance tracking API. All /api/_* endpoints require either a session cookie (browser) or an Authorization: Bearer <token> header (machine clients).
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface WebErrorResponse
 */
export interface WebErrorResponse {
    /**
     * 
     * @type {string}
     * @memberof WebErrorResponse
     */
    error?: string;
}

/**
 * Check if a given object implements the WebErrorResponse interface.
 */
export function instanceOfWebErrorResponse(value: object): value is WebErrorResponse {
    return true;
}

export function WebErrorResponseFromJSON(json: any): WebErrorResponse {
    return WebErrorResponseFromJSONTyped(json, false);
}

export function WebErrorResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): WebErrorResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'error': json['error'] == null ? undefined : json['error'],
    };
}

export function WebErrorResponseToJSON(json: any): WebErrorResponse {
    return WebErrorResponseToJSONTyped(json, false);
}

export function WebErrorResponseToJSONTyped(value?: WebErrorResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'error': value['error'],
    };
}

