/* tslint:disable */
/* eslint-disable */
/**
 * Pago API
 * Personal finance tracking API. All /api/_* endpoints require either a session cookie (browser) or an Authorization: Bearer <token> header (machine clients).
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface WebEditTransactionRequest
 */
export interface WebEditTransactionRequest {
    /**
     * 
     * @type {number}
     * @memberof WebEditTransactionRequest
     */
    amount?: number;
    /**
     * 
     * @type {string}
     * @memberof WebEditTransactionRequest
     */
    category?: string;
    /**
     * 
     * @type {string}
     * @memberof WebEditTransactionRequest
     */
    date?: string;
    /**
     * 
     * @type {string}
     * @memberof WebEditTransactionRequest
     */
    description?: string;
    /**
     * 
     * @type {number}
     * @memberof WebEditTransactionRequest
     */
    id?: number;
}

/**
 * Check if a given object implements the WebEditTransactionRequest interface.
 */
export function instanceOfWebEditTransactionRequest(value: object): value is WebEditTransactionRequest {
    return true;
}

export function WebEditTransactionRequestFromJSON(json: any): WebEditTransactionRequest {
    return WebEditTransactionRequestFromJSONTyped(json, false);
}

export function WebEditTransactionRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): WebEditTransactionRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'amount': json['amount'] == null ? undefined : json['amount'],
        'category': json['category'] == null ? undefined : json['category'],
        'date': json['date'] == null ? undefined : json['date'],
        'description': json['description'] == null ? undefined : json['description'],
        'id': json['id'] == null ? undefined : json['id'],
    };
}

export function WebEditTransactionRequestToJSON(json: any): WebEditTransactionRequest {
    return WebEditTransactionRequestToJSONTyped(json, false);
}

export function WebEditTransactionRequestToJSONTyped(value?: WebEditTransactionRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'amount': value['amount'],
        'category': value['category'],
        'date': value['date'],
        'description': value['description'],
        'id': value['id'],
    };
}

