/* tslint:disable */
/* eslint-disable */
/**
 * Pago API
 * Personal finance tracking API. All /api/_* endpoints require either a session cookie (browser) or an Authorization: Bearer <token> header (machine clients).
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface WebMessageResponse
 */
export interface WebMessageResponse {
    /**
     * 
     * @type {string}
     * @memberof WebMessageResponse
     */
    message?: string;
}

/**
 * Check if a given object implements the WebMessageResponse interface.
 */
export function instanceOfWebMessageResponse(value: object): value is WebMessageResponse {
    return true;
}

export function WebMessageResponseFromJSON(json: any): WebMessageResponse {
    return WebMessageResponseFromJSONTyped(json, false);
}

export function WebMessageResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): WebMessageResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'message': json['message'] == null ? undefined : json['message'],
    };
}

export function WebMessageResponseToJSON(json: any): WebMessageResponse {
    return WebMessageResponseToJSONTyped(json, false);
}

export function WebMessageResponseToJSONTyped(value?: WebMessageResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'message': value['message'],
    };
}

