/* tslint:disable */
/* eslint-disable */
/**
 * Pago API
 * Personal finance tracking API. All /api/_* endpoints require either a session cookie (browser) or an Authorization: Bearer <token> header (machine clients).
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { WebCategoryBreakdown } from './WebCategoryBreakdown';
import {
    WebCategoryBreakdownFromJSON,
    WebCategoryBreakdownFromJSONTyped,
    WebCategoryBreakdownToJSON,
    WebCategoryBreakdownToJSONTyped,
} from './WebCategoryBreakdown';

/**
 * 
 * @export
 * @interface WebMonthlyAnalyticsResponse
 */
export interface WebMonthlyAnalyticsResponse {
    /**
     * 
     * @type {number}
     * @memberof WebMonthlyAnalyticsResponse
     */
    balance?: number;
    /**
     * 
     * @type {WebCategoryBreakdown}
     * @memberof WebMonthlyAnalyticsResponse
     */
    byCategory?: WebCategoryBreakdown;
    /**
     * 
     * @type {string}
     * @memberof WebMonthlyAnalyticsResponse
     */
    month?: string;
    /**
     * 
     * @type {number}
     * @memberof WebMonthlyAnalyticsResponse
     */
    totalExpenses?: number;
    /**
     * 
     * @type {number}
     * @memberof WebMonthlyAnalyticsResponse
     */
    totalIncome?: number;
}

/**
 * Check if a given object implements the WebMonthlyAnalyticsResponse interface.
 */
export function instanceOfWebMonthlyAnalyticsResponse(value: object): value is WebMonthlyAnalyticsResponse {
    return true;
}

export function WebMonthlyAnalyticsResponseFromJSON(json: any): WebMonthlyAnalyticsResponse {
    return WebMonthlyAnalyticsResponseFromJSONTyped(json, false);
}

export function WebMonthlyAnalyticsResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): WebMonthlyAnalyticsResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'balance': json['balance'] == null ? undefined : json['balance'],
        'byCategory': json['byCategory'] == null ? undefined : WebCategoryBreakdownFromJSON(json['byCategory']),
        'month': json['month'] == null ? undefined : json['month'],
        'totalExpenses': json['totalExpenses'] == null ? undefined : json['totalExpenses'],
        'totalIncome': json['totalIncome'] == null ? undefined : json['totalIncome'],
    };
}

export function WebMonthlyAnalyticsResponseToJSON(json: any): WebMonthlyAnalyticsResponse {
    return WebMonthlyAnalyticsResponseToJSONTyped(json, false);
}

export function WebMonthlyAnalyticsResponseToJSONTyped(value?: WebMonthlyAnalyticsResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'balance': value['balance'],
        'byCategory': WebCategoryBreakdownToJSON(value['byCategory']),
        'month': value['month'],
        'totalExpenses': value['totalExpenses'],
        'totalIncome': value['totalIncome'],
    };
}

