/* tslint:disable */
/* eslint-disable */
/**
 * Pago API
 * Personal finance tracking API. All /api/_* endpoints require either a session cookie (browser) or an Authorization: Bearer <token> header (machine clients).
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface WebMonthPoint
 */
export interface WebMonthPoint {
    /**
     * 
     * @type {number}
     * @memberof WebMonthPoint
     */
    balance?: number;
    /**
     * 
     * @type {number}
     * @memberof WebMonthPoint
     */
    expense?: number;
    /**
     * 
     * @type {number}
     * @memberof WebMonthPoint
     */
    income?: number;
    /**
     * 
     * @type {string}
     * @memberof WebMonthPoint
     */
    month?: string;
}

/**
 * Check if a given object implements the WebMonthPoint interface.
 */
export function instanceOfWebMonthPoint(value: object): value is WebMonthPoint {
    return true;
}

export function WebMonthPointFromJSON(json: any): WebMonthPoint {
    return WebMonthPointFromJSONTyped(json, false);
}

export function WebMonthPointFromJSONTyped(json: any, ignoreDiscriminator: boolean): WebMonthPoint {
    if (json == null) {
        return json;
    }
    return {
        
        'balance': json['balance'] == null ? undefined : json['balance'],
        'expense': json['expense'] == null ? undefined : json['expense'],
        'income': json['income'] == null ? undefined : json['income'],
        'month': json['month'] == null ? undefined : json['month'],
    };
}

export function WebMonthPointToJSON(json: any): WebMonthPoint {
    return WebMonthPointToJSONTyped(json, false);
}

export function WebMonthPointToJSONTyped(value?: WebMonthPoint | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'balance': value['balance'],
        'expense': value['expense'],
        'income': value['income'],
        'month': value['month'],
    };
}

