/* tslint:disable */
/* eslint-disable */
/**
 * Pago API
 * Personal finance tracking API. All /api/_* endpoints require either a session cookie (browser) or an Authorization: Bearer <token> header (machine clients).
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { WebTransactionDTO } from './WebTransactionDTO';
import {
    WebTransactionDTOFromJSON,
    WebTransactionDTOFromJSONTyped,
    WebTransactionDTOToJSON,
    WebTransactionDTOToJSONTyped,
} from './WebTransactionDTO';

/**
 * 
 * @export
 * @interface WebSearchTransactionsResponse
 */
export interface WebSearchTransactionsResponse {
    /**
     * 
     * @type {number}
     * @memberof WebSearchTransactionsResponse
     */
    limit?: number;
    /**
     * 
     * @type {number}
     * @memberof WebSearchTransactionsResponse
     */
    offset?: number;
    /**
     * 
     * @type {number}
     * @memberof WebSearchTransactionsResponse
     */
    total?: number;
    /**
     * 
     * @type {Array<WebTransactionDTO>}
     * @memberof WebSearchTransactionsResponse
     */
    transactions?: Array<WebTransactionDTO>;
}

/**
 * Check if a given object implements the WebSearchTransactionsResponse interface.
 */
export function instanceOfWebSearchTransactionsResponse(value: object): value is WebSearchTransactionsResponse {
    return true;
}

export function WebSearchTransactionsResponseFromJSON(json: any): WebSearchTransactionsResponse {
    return WebSearchTransactionsResponseFromJSONTyped(json, false);
}

export function WebSearchTransactionsResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): WebSearchTransactionsResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'limit': json['limit'] == null ? undefined : json['limit'],
        'offset': json['offset'] == null ? undefined : json['offset'],
        'total': json['total'] == null ? undefined : json['total'],
        'transactions': json['transactions'] == null ? undefined : ((json['transactions'] as Array<any>).map(WebTransactionDTOFromJSON)),
    };
}

export function WebSearchTransactionsResponseToJSON(json: any): WebSearchTransactionsResponse {
    return WebSearchTransactionsResponseToJSONTyped(json, false);
}

export function WebSearchTransactionsResponseToJSONTyped(value?: WebSearchTransactionsResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'limit': value['limit'],
        'offset': value['offset'],
        'total': value['total'],
        'transactions': value['transactions'] == null ? undefined : ((value['transactions'] as Array<any>).map(WebTransactionDTOToJSON)),
    };
}

