/* tslint:disable */
/* eslint-disable */
/**
 * Pago API
 * Personal finance tracking API. All /api/_* endpoints require either a session cookie (browser) or an Authorization: Bearer <token> header (machine clients).
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface WebSearchTransactionsRequest
 */
export interface WebSearchTransactionsRequest {
    /**
     * 
     * @type {number}
     * @memberof WebSearchTransactionsRequest
     */
    amountMax?: number;
    /**
     * 
     * @type {number}
     * @memberof WebSearchTransactionsRequest
     */
    amountMin?: number;
    /**
     * 
     * @type {string}
     * @memberof WebSearchTransactionsRequest
     */
    category?: string;
    /**
     * 
     * @type {string}
     * @memberof WebSearchTransactionsRequest
     */
    dateFrom?: string;
    /**
     * 
     * @type {string}
     * @memberof WebSearchTransactionsRequest
     */
    dateTo?: string;
    /**
     * 
     * @type {number}
     * @memberof WebSearchTransactionsRequest
     */
    limit?: number;
    /**
     * 
     * @type {number}
     * @memberof WebSearchTransactionsRequest
     */
    offset?: number;
    /**
     * 
     * @type {string}
     * @memberof WebSearchTransactionsRequest
     */
    query?: string;
    /**
     * 
     * @type {string}
     * @memberof WebSearchTransactionsRequest
     */
    type?: string;
}

/**
 * Check if a given object implements the WebSearchTransactionsRequest interface.
 */
export function instanceOfWebSearchTransactionsRequest(value: object): value is WebSearchTransactionsRequest {
    return true;
}

export function WebSearchTransactionsRequestFromJSON(json: any): WebSearchTransactionsRequest {
    return WebSearchTransactionsRequestFromJSONTyped(json, false);
}

export function WebSearchTransactionsRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): WebSearchTransactionsRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'amountMax': json['amountMax'] == null ? undefined : json['amountMax'],
        'amountMin': json['amountMin'] == null ? undefined : json['amountMin'],
        'category': json['category'] == null ? undefined : json['category'],
        'dateFrom': json['dateFrom'] == null ? undefined : json['dateFrom'],
        'dateTo': json['dateTo'] == null ? undefined : json['dateTo'],
        'limit': json['limit'] == null ? undefined : json['limit'],
        'offset': json['offset'] == null ? undefined : json['offset'],
        'query': json['query'] == null ? undefined : json['query'],
        'type': json['type'] == null ? undefined : json['type'],
    };
}

export function WebSearchTransactionsRequestToJSON(json: any): WebSearchTransactionsRequest {
    return WebSearchTransactionsRequestToJSONTyped(json, false);
}

export function WebSearchTransactionsRequestToJSONTyped(value?: WebSearchTransactionsRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'amountMax': value['amountMax'],
        'amountMin': value['amountMin'],
        'category': value['category'],
        'dateFrom': value['dateFrom'],
        'dateTo': value['dateTo'],
        'limit': value['limit'],
        'offset': value['offset'],
        'query': value['query'],
        'type': value['type'],
    };
}

