/* tslint:disable */
/* eslint-disable */
/**
 * Pago API
 * Personal finance tracking API. All /api/_* endpoints require either a session cookie (browser) or an Authorization: Bearer <token> header (machine clients).
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface WebStatsResponse
 */
export interface WebStatsResponse {
    /**
     * 
     * @type {number}
     * @memberof WebStatsResponse
     */
    balance?: number;
    /**
     * 
     * @type {number}
     * @memberof WebStatsResponse
     */
    totalExpenses?: number;
    /**
     * 
     * @type {number}
     * @memberof WebStatsResponse
     */
    totalIncome?: number;
    /**
     * 
     * @type {number}
     * @memberof WebStatsResponse
     */
    totalTransactions?: number;
}

/**
 * Check if a given object implements the WebStatsResponse interface.
 */
export function instanceOfWebStatsResponse(value: object): value is WebStatsResponse {
    return true;
}

export function WebStatsResponseFromJSON(json: any): WebStatsResponse {
    return WebStatsResponseFromJSONTyped(json, false);
}

export function WebStatsResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): WebStatsResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'balance': json['balance'] == null ? undefined : json['balance'],
        'totalExpenses': json['totalExpenses'] == null ? undefined : json['totalExpenses'],
        'totalIncome': json['totalIncome'] == null ? undefined : json['totalIncome'],
        'totalTransactions': json['totalTransactions'] == null ? undefined : json['totalTransactions'],
    };
}

export function WebStatsResponseToJSON(json: any): WebStatsResponse {
    return WebStatsResponseToJSONTyped(json, false);
}

export function WebStatsResponseToJSONTyped(value?: WebStatsResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'balance': value['balance'],
        'totalExpenses': value['totalExpenses'],
        'totalIncome': value['totalIncome'],
        'totalTransactions': value['totalTransactions'],
    };
}

