/* tslint:disable */
/* eslint-disable */
/**
 * Pago API
 * Personal finance tracking API. All /api/_* endpoints require either a session cookie (browser) or an Authorization: Bearer <token> header (machine clients).
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { WebMonthPoint } from './WebMonthPoint';
import {
    WebMonthPointFromJSON,
    WebMonthPointFromJSONTyped,
    WebMonthPointToJSON,
    WebMonthPointToJSONTyped,
} from './WebMonthPoint';

/**
 * 
 * @export
 * @interface WebTrendResponse
 */
export interface WebTrendResponse {
    /**
     * 
     * @type {string}
     * @memberof WebTrendResponse
     */
    from?: string;
    /**
     * 
     * @type {Array<WebMonthPoint>}
     * @memberof WebTrendResponse
     */
    points?: Array<WebMonthPoint>;
    /**
     * 
     * @type {string}
     * @memberof WebTrendResponse
     */
    to?: string;
}

/**
 * Check if a given object implements the WebTrendResponse interface.
 */
export function instanceOfWebTrendResponse(value: object): value is WebTrendResponse {
    return true;
}

export function WebTrendResponseFromJSON(json: any): WebTrendResponse {
    return WebTrendResponseFromJSONTyped(json, false);
}

export function WebTrendResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): WebTrendResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'from': json['from'] == null ? undefined : json['from'],
        'points': json['points'] == null ? undefined : ((json['points'] as Array<any>).map(WebMonthPointFromJSON)),
        'to': json['to'] == null ? undefined : json['to'],
    };
}

export function WebTrendResponseToJSON(json: any): WebTrendResponse {
    return WebTrendResponseToJSONTyped(json, false);
}

export function WebTrendResponseToJSONTyped(value?: WebTrendResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'from': value['from'],
        'points': value['points'] == null ? undefined : ((value['points'] as Array<any>).map(WebMonthPointToJSON)),
        'to': value['to'],
    };
}

