/* tslint:disable */
/* eslint-disable */
/**
 * Pago API
 * Personal finance tracking API. All /api/_* endpoints require either a session cookie (browser) or an Authorization: Bearer <token> header (machine clients).
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface WebTransactionDTO
 */
export interface WebTransactionDTO {
    /**
     * 
     * @type {number}
     * @memberof WebTransactionDTO
     */
    amount?: number;
    /**
     * 
     * @type {string}
     * @memberof WebTransactionDTO
     */
    category?: string;
    /**
     * 
     * @type {string}
     * @memberof WebTransactionDTO
     */
    date?: string;
    /**
     * 
     * @type {string}
     * @memberof WebTransactionDTO
     */
    description?: string;
    /**
     * 
     * @type {number}
     * @memberof WebTransactionDTO
     */
    id?: number;
    /**
     * 
     * @type {string}
     * @memberof WebTransactionDTO
     */
    type?: string;
}

/**
 * Check if a given object implements the WebTransactionDTO interface.
 */
export function instanceOfWebTransactionDTO(value: object): value is WebTransactionDTO {
    return true;
}

export function WebTransactionDTOFromJSON(json: any): WebTransactionDTO {
    return WebTransactionDTOFromJSONTyped(json, false);
}

export function WebTransactionDTOFromJSONTyped(json: any, ignoreDiscriminator: boolean): WebTransactionDTO {
    if (json == null) {
        return json;
    }
    return {
        
        'amount': json['amount'] == null ? undefined : json['amount'],
        'category': json['category'] == null ? undefined : json['category'],
        'date': json['date'] == null ? undefined : json['date'],
        'description': json['description'] == null ? undefined : json['description'],
        'id': json['id'] == null ? undefined : json['id'],
        'type': json['type'] == null ? undefined : json['type'],
    };
}

export function WebTransactionDTOToJSON(json: any): WebTransactionDTO {
    return WebTransactionDTOToJSONTyped(json, false);
}

export function WebTransactionDTOToJSONTyped(value?: WebTransactionDTO | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'amount': value['amount'],
        'category': value['category'],
        'date': value['date'],
        'description': value['description'],
        'id': value['id'],
        'type': value['type'],
    };
}

