/* tslint:disable */
/* eslint-disable */
/**
 * Pago API
 * Personal finance tracking API. All /api/_* endpoints require either a session cookie (browser) or an Authorization: Bearer <token> header (machine clients).
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { WebTransactionDTO } from './WebTransactionDTO';
import {
    WebTransactionDTOFromJSON,
    WebTransactionDTOFromJSONTyped,
    WebTransactionDTOToJSON,
    WebTransactionDTOToJSONTyped,
} from './WebTransactionDTO';

/**
 * 
 * @export
 * @interface WebTransactionsResponse
 */
export interface WebTransactionsResponse {
    /**
     * 
     * @type {number}
     * @memberof WebTransactionsResponse
     */
    count?: number;
    /**
     * 
     * @type {Array<WebTransactionDTO>}
     * @memberof WebTransactionsResponse
     */
    transactions?: Array<WebTransactionDTO>;
}

/**
 * Check if a given object implements the WebTransactionsResponse interface.
 */
export function instanceOfWebTransactionsResponse(value: object): value is WebTransactionsResponse {
    return true;
}

export function WebTransactionsResponseFromJSON(json: any): WebTransactionsResponse {
    return WebTransactionsResponseFromJSONTyped(json, false);
}

export function WebTransactionsResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): WebTransactionsResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'count': json['count'] == null ? undefined : json['count'],
        'transactions': json['transactions'] == null ? undefined : ((json['transactions'] as Array<any>).map(WebTransactionDTOFromJSON)),
    };
}

export function WebTransactionsResponseToJSON(json: any): WebTransactionsResponse {
    return WebTransactionsResponseToJSONTyped(json, false);
}

export function WebTransactionsResponseToJSONTyped(value?: WebTransactionsResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'count': value['count'],
        'transactions': value['transactions'] == null ? undefined : ((value['transactions'] as Array<any>).map(WebTransactionDTOToJSON)),
    };
}

