/* tslint:disable */
/* eslint-disable */
/**
 * Pago API
 * Personal finance tracking API. All /api/_* endpoints require either a session cookie (browser) or an Authorization: Bearer <token> header (machine clients).
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface WebYearMonthEntry
 */
export interface WebYearMonthEntry {
    /**
     * 
     * @type {number}
     * @memberof WebYearMonthEntry
     */
    balance?: number;
    /**
     * 
     * @type {number}
     * @memberof WebYearMonthEntry
     */
    expense?: number;
    /**
     * 
     * @type {number}
     * @memberof WebYearMonthEntry
     */
    income?: number;
    /**
     * 
     * @type {number}
     * @memberof WebYearMonthEntry
     */
    month?: number;
}

/**
 * Check if a given object implements the WebYearMonthEntry interface.
 */
export function instanceOfWebYearMonthEntry(value: object): value is WebYearMonthEntry {
    return true;
}

export function WebYearMonthEntryFromJSON(json: any): WebYearMonthEntry {
    return WebYearMonthEntryFromJSONTyped(json, false);
}

export function WebYearMonthEntryFromJSONTyped(json: any, ignoreDiscriminator: boolean): WebYearMonthEntry {
    if (json == null) {
        return json;
    }
    return {
        
        'balance': json['balance'] == null ? undefined : json['balance'],
        'expense': json['expense'] == null ? undefined : json['expense'],
        'income': json['income'] == null ? undefined : json['income'],
        'month': json['month'] == null ? undefined : json['month'],
    };
}

export function WebYearMonthEntryToJSON(json: any): WebYearMonthEntry {
    return WebYearMonthEntryToJSONTyped(json, false);
}

export function WebYearMonthEntryToJSONTyped(value?: WebYearMonthEntry | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'balance': value['balance'],
        'expense': value['expense'],
        'income': value['income'],
        'month': value['month'],
    };
}

