/* tslint:disable */
/* eslint-disable */
/**
 * Pago API
 * Personal finance tracking API. All /api/_* endpoints require either a session cookie (browser) or an Authorization: Bearer <token> header (machine clients).
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  WebErrorResponse,
  WebMonthlyAnalyticsResponse,
  WebTrendResponse,
  WebYearAnalyticsResponse,
} from '../models/index';
import {
    WebErrorResponseFromJSON,
    WebErrorResponseToJSON,
    WebMonthlyAnalyticsResponseFromJSON,
    WebMonthlyAnalyticsResponseToJSON,
    WebTrendResponseFromJSON,
    WebTrendResponseToJSON,
    WebYearAnalyticsResponseFromJSON,
    WebYearAnalyticsResponseToJSON,
} from '../models/index';

export interface ApiAnalyticsMonthlyGetRequest {
    month?: string;
}

export interface ApiAnalyticsTrendGetRequest {
    months?: number;
}

export interface ApiAnalyticsYearGetRequest {
    year?: number;
}

/**
 * 
 */
export class AnalyticsApi extends runtime.BaseAPI {

    /**
     * Returns total income/expenses and per-category aggregates for a given month.
     * Monthly category breakdown
     */
    async apiAnalyticsMonthlyGetRaw(requestParameters: ApiAnalyticsMonthlyGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<WebMonthlyAnalyticsResponse>> {
        const queryParameters: any = {};

        if (requestParameters['month'] != null) {
            queryParameters['month'] = requestParameters['month'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Authorization"] = await this.configuration.apiKey("Authorization"); // BearerAuth authentication
        }


        let urlPath = `/api/analytics/monthly`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => WebMonthlyAnalyticsResponseFromJSON(jsonValue));
    }

    /**
     * Returns total income/expenses and per-category aggregates for a given month.
     * Monthly category breakdown
     */
    async apiAnalyticsMonthlyGet(requestParameters: ApiAnalyticsMonthlyGetRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<WebMonthlyAnalyticsResponse> {
        const response = await this.apiAnalyticsMonthlyGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Monthly trend over the trailing N months
     */
    async apiAnalyticsTrendGetRaw(requestParameters: ApiAnalyticsTrendGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<WebTrendResponse>> {
        const queryParameters: any = {};

        if (requestParameters['months'] != null) {
            queryParameters['months'] = requestParameters['months'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Authorization"] = await this.configuration.apiKey("Authorization"); // BearerAuth authentication
        }


        let urlPath = `/api/analytics/trend`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => WebTrendResponseFromJSON(jsonValue));
    }

    /**
     * Monthly trend over the trailing N months
     */
    async apiAnalyticsTrendGet(requestParameters: ApiAnalyticsTrendGetRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<WebTrendResponse> {
        const response = await this.apiAnalyticsTrendGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Annual breakdown by month and category
     */
    async apiAnalyticsYearGetRaw(requestParameters: ApiAnalyticsYearGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<WebYearAnalyticsResponse>> {
        const queryParameters: any = {};

        if (requestParameters['year'] != null) {
            queryParameters['year'] = requestParameters['year'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Authorization"] = await this.configuration.apiKey("Authorization"); // BearerAuth authentication
        }


        let urlPath = `/api/analytics/year`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => WebYearAnalyticsResponseFromJSON(jsonValue));
    }

    /**
     * Annual breakdown by month and category
     */
    async apiAnalyticsYearGet(requestParameters: ApiAnalyticsYearGetRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<WebYearAnalyticsResponse> {
        const response = await this.apiAnalyticsYearGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
