/* tslint:disable */
/* eslint-disable */
/**
 * Pago API
 * Personal finance tracking API. All /api/_* endpoints require either a session cookie (browser) or an Authorization: Bearer <token> header (machine clients).
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  WebBudgetResponse,
  WebBudgetUpsertRequest,
  WebErrorResponse,
} from '../models/index';
import {
    WebBudgetResponseFromJSON,
    WebBudgetResponseToJSON,
    WebBudgetUpsertRequestFromJSON,
    WebBudgetUpsertRequestToJSON,
    WebErrorResponseFromJSON,
    WebErrorResponseToJSON,
} from '../models/index';

export interface ApiBudgetDeleteRequest {
    body: WebBudgetUpsertRequest;
}

export interface ApiBudgetDelete0Request {
    body: WebBudgetUpsertRequest;
}

export interface ApiBudgetDelete1Request {
    body: WebBudgetUpsertRequest;
}

export interface ApiBudgetDelete2Request {
    body: WebBudgetUpsertRequest;
}

export interface ApiBudgetGetRequest {
    body: WebBudgetUpsertRequest;
}

export interface ApiBudgetGet0Request {
    body: WebBudgetUpsertRequest;
}

export interface ApiBudgetGet1Request {
    body: WebBudgetUpsertRequest;
}

export interface ApiBudgetGet2Request {
    body: WebBudgetUpsertRequest;
}

export interface ApiBudgetPostRequest {
    body: WebBudgetUpsertRequest;
}

export interface ApiBudgetPost0Request {
    body: WebBudgetUpsertRequest;
}

export interface ApiBudgetPost1Request {
    body: WebBudgetUpsertRequest;
}

export interface ApiBudgetPost2Request {
    body: WebBudgetUpsertRequest;
}

export interface ApiBudgetPutRequest {
    body: WebBudgetUpsertRequest;
}

export interface ApiBudgetPut0Request {
    body: WebBudgetUpsertRequest;
}

export interface ApiBudgetPut1Request {
    body: WebBudgetUpsertRequest;
}

export interface ApiBudgetPut2Request {
    body: WebBudgetUpsertRequest;
}

/**
 * 
 */
export class BudgetApi extends runtime.BaseAPI {

    /**
     * Delete the monthly budget
     */
    async apiBudgetDeleteRaw(requestParameters: ApiBudgetDeleteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<WebBudgetResponse>> {
        if (requestParameters['body'] == null) {
            throw new runtime.RequiredError(
                'body',
                'Required parameter "body" was null or undefined when calling apiBudgetDelete().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Authorization"] = await this.configuration.apiKey("Authorization"); // BearerAuth authentication
        }


        let urlPath = `/api/budget`;

        const response = await this.request({
            path: urlPath,
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
            body: WebBudgetUpsertRequestToJSON(requestParameters['body']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => WebBudgetResponseFromJSON(jsonValue));
    }

    /**
     * Delete the monthly budget
     */
    async apiBudgetDelete(requestParameters: ApiBudgetDeleteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<WebBudgetResponse> {
        const response = await this.apiBudgetDeleteRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Delete the monthly budget
     */
    async apiBudgetDelete_1Raw(requestParameters: ApiBudgetDelete0Request, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<WebBudgetResponse>> {
        if (requestParameters['body'] == null) {
            throw new runtime.RequiredError(
                'body',
                'Required parameter "body" was null or undefined when calling apiBudgetDelete_1().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Authorization"] = await this.configuration.apiKey("Authorization"); // BearerAuth authentication
        }


        let urlPath = `/api/budget`;

        const response = await this.request({
            path: urlPath,
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
            body: WebBudgetUpsertRequestToJSON(requestParameters['body']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => WebBudgetResponseFromJSON(jsonValue));
    }

    /**
     * Delete the monthly budget
     */
    async apiBudgetDelete_1(requestParameters: ApiBudgetDelete0Request, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<WebBudgetResponse> {
        const response = await this.apiBudgetDelete_1Raw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Delete the monthly budget
     */
    async apiBudgetDelete_2Raw(requestParameters: ApiBudgetDelete1Request, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<WebBudgetResponse>> {
        if (requestParameters['body'] == null) {
            throw new runtime.RequiredError(
                'body',
                'Required parameter "body" was null or undefined when calling apiBudgetDelete_2().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Authorization"] = await this.configuration.apiKey("Authorization"); // BearerAuth authentication
        }


        let urlPath = `/api/budget`;

        const response = await this.request({
            path: urlPath,
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
            body: WebBudgetUpsertRequestToJSON(requestParameters['body']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => WebBudgetResponseFromJSON(jsonValue));
    }

    /**
     * Delete the monthly budget
     */
    async apiBudgetDelete_2(requestParameters: ApiBudgetDelete1Request, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<WebBudgetResponse> {
        const response = await this.apiBudgetDelete_2Raw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Delete the monthly budget
     */
    async apiBudgetDelete_3Raw(requestParameters: ApiBudgetDelete2Request, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<WebBudgetResponse>> {
        if (requestParameters['body'] == null) {
            throw new runtime.RequiredError(
                'body',
                'Required parameter "body" was null or undefined when calling apiBudgetDelete_3().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Authorization"] = await this.configuration.apiKey("Authorization"); // BearerAuth authentication
        }


        let urlPath = `/api/budget`;

        const response = await this.request({
            path: urlPath,
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
            body: WebBudgetUpsertRequestToJSON(requestParameters['body']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => WebBudgetResponseFromJSON(jsonValue));
    }

    /**
     * Delete the monthly budget
     */
    async apiBudgetDelete_3(requestParameters: ApiBudgetDelete2Request, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<WebBudgetResponse> {
        const response = await this.apiBudgetDelete_3Raw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Delete the monthly budget
     */
    async apiBudgetGetRaw(requestParameters: ApiBudgetGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<WebBudgetResponse>> {
        if (requestParameters['body'] == null) {
            throw new runtime.RequiredError(
                'body',
                'Required parameter "body" was null or undefined when calling apiBudgetGet().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Authorization"] = await this.configuration.apiKey("Authorization"); // BearerAuth authentication
        }


        let urlPath = `/api/budget`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
            body: WebBudgetUpsertRequestToJSON(requestParameters['body']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => WebBudgetResponseFromJSON(jsonValue));
    }

    /**
     * Delete the monthly budget
     */
    async apiBudgetGet(requestParameters: ApiBudgetGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<WebBudgetResponse> {
        const response = await this.apiBudgetGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Delete the monthly budget
     */
    async apiBudgetGet_4Raw(requestParameters: ApiBudgetGet0Request, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<WebBudgetResponse>> {
        if (requestParameters['body'] == null) {
            throw new runtime.RequiredError(
                'body',
                'Required parameter "body" was null or undefined when calling apiBudgetGet_4().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Authorization"] = await this.configuration.apiKey("Authorization"); // BearerAuth authentication
        }


        let urlPath = `/api/budget`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
            body: WebBudgetUpsertRequestToJSON(requestParameters['body']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => WebBudgetResponseFromJSON(jsonValue));
    }

    /**
     * Delete the monthly budget
     */
    async apiBudgetGet_4(requestParameters: ApiBudgetGet0Request, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<WebBudgetResponse> {
        const response = await this.apiBudgetGet_4Raw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Delete the monthly budget
     */
    async apiBudgetGet_5Raw(requestParameters: ApiBudgetGet1Request, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<WebBudgetResponse>> {
        if (requestParameters['body'] == null) {
            throw new runtime.RequiredError(
                'body',
                'Required parameter "body" was null or undefined when calling apiBudgetGet_5().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Authorization"] = await this.configuration.apiKey("Authorization"); // BearerAuth authentication
        }


        let urlPath = `/api/budget`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
            body: WebBudgetUpsertRequestToJSON(requestParameters['body']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => WebBudgetResponseFromJSON(jsonValue));
    }

    /**
     * Delete the monthly budget
     */
    async apiBudgetGet_5(requestParameters: ApiBudgetGet1Request, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<WebBudgetResponse> {
        const response = await this.apiBudgetGet_5Raw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Delete the monthly budget
     */
    async apiBudgetGet_6Raw(requestParameters: ApiBudgetGet2Request, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<WebBudgetResponse>> {
        if (requestParameters['body'] == null) {
            throw new runtime.RequiredError(
                'body',
                'Required parameter "body" was null or undefined when calling apiBudgetGet_6().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Authorization"] = await this.configuration.apiKey("Authorization"); // BearerAuth authentication
        }


        let urlPath = `/api/budget`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
            body: WebBudgetUpsertRequestToJSON(requestParameters['body']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => WebBudgetResponseFromJSON(jsonValue));
    }

    /**
     * Delete the monthly budget
     */
    async apiBudgetGet_6(requestParameters: ApiBudgetGet2Request, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<WebBudgetResponse> {
        const response = await this.apiBudgetGet_6Raw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Delete the monthly budget
     */
    async apiBudgetPostRaw(requestParameters: ApiBudgetPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<WebBudgetResponse>> {
        if (requestParameters['body'] == null) {
            throw new runtime.RequiredError(
                'body',
                'Required parameter "body" was null or undefined when calling apiBudgetPost().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Authorization"] = await this.configuration.apiKey("Authorization"); // BearerAuth authentication
        }


        let urlPath = `/api/budget`;

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: WebBudgetUpsertRequestToJSON(requestParameters['body']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => WebBudgetResponseFromJSON(jsonValue));
    }

    /**
     * Delete the monthly budget
     */
    async apiBudgetPost(requestParameters: ApiBudgetPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<WebBudgetResponse> {
        const response = await this.apiBudgetPostRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Delete the monthly budget
     */
    async apiBudgetPost_7Raw(requestParameters: ApiBudgetPost0Request, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<WebBudgetResponse>> {
        if (requestParameters['body'] == null) {
            throw new runtime.RequiredError(
                'body',
                'Required parameter "body" was null or undefined when calling apiBudgetPost_7().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Authorization"] = await this.configuration.apiKey("Authorization"); // BearerAuth authentication
        }


        let urlPath = `/api/budget`;

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: WebBudgetUpsertRequestToJSON(requestParameters['body']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => WebBudgetResponseFromJSON(jsonValue));
    }

    /**
     * Delete the monthly budget
     */
    async apiBudgetPost_7(requestParameters: ApiBudgetPost0Request, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<WebBudgetResponse> {
        const response = await this.apiBudgetPost_7Raw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Delete the monthly budget
     */
    async apiBudgetPost_8Raw(requestParameters: ApiBudgetPost1Request, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<WebBudgetResponse>> {
        if (requestParameters['body'] == null) {
            throw new runtime.RequiredError(
                'body',
                'Required parameter "body" was null or undefined when calling apiBudgetPost_8().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Authorization"] = await this.configuration.apiKey("Authorization"); // BearerAuth authentication
        }


        let urlPath = `/api/budget`;

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: WebBudgetUpsertRequestToJSON(requestParameters['body']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => WebBudgetResponseFromJSON(jsonValue));
    }

    /**
     * Delete the monthly budget
     */
    async apiBudgetPost_8(requestParameters: ApiBudgetPost1Request, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<WebBudgetResponse> {
        const response = await this.apiBudgetPost_8Raw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Delete the monthly budget
     */
    async apiBudgetPost_9Raw(requestParameters: ApiBudgetPost2Request, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<WebBudgetResponse>> {
        if (requestParameters['body'] == null) {
            throw new runtime.RequiredError(
                'body',
                'Required parameter "body" was null or undefined when calling apiBudgetPost_9().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Authorization"] = await this.configuration.apiKey("Authorization"); // BearerAuth authentication
        }


        let urlPath = `/api/budget`;

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: WebBudgetUpsertRequestToJSON(requestParameters['body']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => WebBudgetResponseFromJSON(jsonValue));
    }

    /**
     * Delete the monthly budget
     */
    async apiBudgetPost_9(requestParameters: ApiBudgetPost2Request, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<WebBudgetResponse> {
        const response = await this.apiBudgetPost_9Raw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Delete the monthly budget
     */
    async apiBudgetPutRaw(requestParameters: ApiBudgetPutRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<WebBudgetResponse>> {
        if (requestParameters['body'] == null) {
            throw new runtime.RequiredError(
                'body',
                'Required parameter "body" was null or undefined when calling apiBudgetPut().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Authorization"] = await this.configuration.apiKey("Authorization"); // BearerAuth authentication
        }


        let urlPath = `/api/budget`;

        const response = await this.request({
            path: urlPath,
            method: 'PUT',
            headers: headerParameters,
            query: queryParameters,
            body: WebBudgetUpsertRequestToJSON(requestParameters['body']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => WebBudgetResponseFromJSON(jsonValue));
    }

    /**
     * Delete the monthly budget
     */
    async apiBudgetPut(requestParameters: ApiBudgetPutRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<WebBudgetResponse> {
        const response = await this.apiBudgetPutRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Delete the monthly budget
     */
    async apiBudgetPut_10Raw(requestParameters: ApiBudgetPut0Request, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<WebBudgetResponse>> {
        if (requestParameters['body'] == null) {
            throw new runtime.RequiredError(
                'body',
                'Required parameter "body" was null or undefined when calling apiBudgetPut_10().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Authorization"] = await this.configuration.apiKey("Authorization"); // BearerAuth authentication
        }


        let urlPath = `/api/budget`;

        const response = await this.request({
            path: urlPath,
            method: 'PUT',
            headers: headerParameters,
            query: queryParameters,
            body: WebBudgetUpsertRequestToJSON(requestParameters['body']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => WebBudgetResponseFromJSON(jsonValue));
    }

    /**
     * Delete the monthly budget
     */
    async apiBudgetPut_10(requestParameters: ApiBudgetPut0Request, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<WebBudgetResponse> {
        const response = await this.apiBudgetPut_10Raw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Delete the monthly budget
     */
    async apiBudgetPut_11Raw(requestParameters: ApiBudgetPut1Request, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<WebBudgetResponse>> {
        if (requestParameters['body'] == null) {
            throw new runtime.RequiredError(
                'body',
                'Required parameter "body" was null or undefined when calling apiBudgetPut_11().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Authorization"] = await this.configuration.apiKey("Authorization"); // BearerAuth authentication
        }


        let urlPath = `/api/budget`;

        const response = await this.request({
            path: urlPath,
            method: 'PUT',
            headers: headerParameters,
            query: queryParameters,
            body: WebBudgetUpsertRequestToJSON(requestParameters['body']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => WebBudgetResponseFromJSON(jsonValue));
    }

    /**
     * Delete the monthly budget
     */
    async apiBudgetPut_11(requestParameters: ApiBudgetPut1Request, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<WebBudgetResponse> {
        const response = await this.apiBudgetPut_11Raw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Delete the monthly budget
     */
    async apiBudgetPut_12Raw(requestParameters: ApiBudgetPut2Request, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<WebBudgetResponse>> {
        if (requestParameters['body'] == null) {
            throw new runtime.RequiredError(
                'body',
                'Required parameter "body" was null or undefined when calling apiBudgetPut_12().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Authorization"] = await this.configuration.apiKey("Authorization"); // BearerAuth authentication
        }


        let urlPath = `/api/budget`;

        const response = await this.request({
            path: urlPath,
            method: 'PUT',
            headers: headerParameters,
            query: queryParameters,
            body: WebBudgetUpsertRequestToJSON(requestParameters['body']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => WebBudgetResponseFromJSON(jsonValue));
    }

    /**
     * Delete the monthly budget
     */
    async apiBudgetPut_12(requestParameters: ApiBudgetPut2Request, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<WebBudgetResponse> {
        const response = await this.apiBudgetPut_12Raw(requestParameters, initOverrides);
        return await response.value();
    }

}
