/*
Pago API

Personal finance tracking API. All /api/_* endpoints require either a session cookie (browser) or an Authorization: Bearer <token> header (machine clients).

API version: 1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package pago

import (
	"encoding/json"
)

// checks if the WebMessageResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &WebMessageResponse{}

// WebMessageResponse struct for WebMessageResponse
type WebMessageResponse struct {
	Message *string `json:"message,omitempty"`
}

// NewWebMessageResponse instantiates a new WebMessageResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewWebMessageResponse() *WebMessageResponse {
	this := WebMessageResponse{}
	return &this
}

// NewWebMessageResponseWithDefaults instantiates a new WebMessageResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewWebMessageResponseWithDefaults() *WebMessageResponse {
	this := WebMessageResponse{}
	return &this
}

// GetMessage returns the Message field value if set, zero value otherwise.
func (o *WebMessageResponse) GetMessage() string {
	if o == nil || IsNil(o.Message) {
		var ret string
		return ret
	}
	return *o.Message
}

// GetMessageOk returns a tuple with the Message field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *WebMessageResponse) GetMessageOk() (*string, bool) {
	if o == nil || IsNil(o.Message) {
		return nil, false
	}
	return o.Message, true
}

// HasMessage returns a boolean if a field has been set.
func (o *WebMessageResponse) HasMessage() bool {
	if o != nil && !IsNil(o.Message) {
		return true
	}

	return false
}

// SetMessage gets a reference to the given string and assigns it to the Message field.
func (o *WebMessageResponse) SetMessage(v string) {
	o.Message = &v
}

func (o WebMessageResponse) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o WebMessageResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Message) {
		toSerialize["message"] = o.Message
	}
	return toSerialize, nil
}

type NullableWebMessageResponse struct {
	value *WebMessageResponse
	isSet bool
}

func (v NullableWebMessageResponse) Get() *WebMessageResponse {
	return v.value
}

func (v *NullableWebMessageResponse) Set(val *WebMessageResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableWebMessageResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableWebMessageResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableWebMessageResponse(val *WebMessageResponse) *NullableWebMessageResponse {
	return &NullableWebMessageResponse{value: val, isSet: true}
}

func (v NullableWebMessageResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableWebMessageResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
