/*
Pago API

Personal finance tracking API. All /api/_* endpoints require either a session cookie (browser) or an Authorization: Bearer <token> header (machine clients).

API version: 1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package pago

import (
	"encoding/json"
)

// checks if the WebTrendResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &WebTrendResponse{}

// WebTrendResponse struct for WebTrendResponse
type WebTrendResponse struct {
	From   *string         `json:"from,omitempty"`
	Points []WebMonthPoint `json:"points,omitempty"`
	To     *string         `json:"to,omitempty"`
}

// NewWebTrendResponse instantiates a new WebTrendResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewWebTrendResponse() *WebTrendResponse {
	this := WebTrendResponse{}
	return &this
}

// NewWebTrendResponseWithDefaults instantiates a new WebTrendResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewWebTrendResponseWithDefaults() *WebTrendResponse {
	this := WebTrendResponse{}
	return &this
}

// GetFrom returns the From field value if set, zero value otherwise.
func (o *WebTrendResponse) GetFrom() string {
	if o == nil || IsNil(o.From) {
		var ret string
		return ret
	}
	return *o.From
}

// GetFromOk returns a tuple with the From field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *WebTrendResponse) GetFromOk() (*string, bool) {
	if o == nil || IsNil(o.From) {
		return nil, false
	}
	return o.From, true
}

// HasFrom returns a boolean if a field has been set.
func (o *WebTrendResponse) HasFrom() bool {
	if o != nil && !IsNil(o.From) {
		return true
	}

	return false
}

// SetFrom gets a reference to the given string and assigns it to the From field.
func (o *WebTrendResponse) SetFrom(v string) {
	o.From = &v
}

// GetPoints returns the Points field value if set, zero value otherwise.
func (o *WebTrendResponse) GetPoints() []WebMonthPoint {
	if o == nil || IsNil(o.Points) {
		var ret []WebMonthPoint
		return ret
	}
	return o.Points
}

// GetPointsOk returns a tuple with the Points field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *WebTrendResponse) GetPointsOk() ([]WebMonthPoint, bool) {
	if o == nil || IsNil(o.Points) {
		return nil, false
	}
	return o.Points, true
}

// HasPoints returns a boolean if a field has been set.
func (o *WebTrendResponse) HasPoints() bool {
	if o != nil && !IsNil(o.Points) {
		return true
	}

	return false
}

// SetPoints gets a reference to the given []WebMonthPoint and assigns it to the Points field.
func (o *WebTrendResponse) SetPoints(v []WebMonthPoint) {
	o.Points = v
}

// GetTo returns the To field value if set, zero value otherwise.
func (o *WebTrendResponse) GetTo() string {
	if o == nil || IsNil(o.To) {
		var ret string
		return ret
	}
	return *o.To
}

// GetToOk returns a tuple with the To field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *WebTrendResponse) GetToOk() (*string, bool) {
	if o == nil || IsNil(o.To) {
		return nil, false
	}
	return o.To, true
}

// HasTo returns a boolean if a field has been set.
func (o *WebTrendResponse) HasTo() bool {
	if o != nil && !IsNil(o.To) {
		return true
	}

	return false
}

// SetTo gets a reference to the given string and assigns it to the To field.
func (o *WebTrendResponse) SetTo(v string) {
	o.To = &v
}

func (o WebTrendResponse) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o WebTrendResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.From) {
		toSerialize["from"] = o.From
	}
	if !IsNil(o.Points) {
		toSerialize["points"] = o.Points
	}
	if !IsNil(o.To) {
		toSerialize["to"] = o.To
	}
	return toSerialize, nil
}

type NullableWebTrendResponse struct {
	value *WebTrendResponse
	isSet bool
}

func (v NullableWebTrendResponse) Get() *WebTrendResponse {
	return v.value
}

func (v *NullableWebTrendResponse) Set(val *WebTrendResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableWebTrendResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableWebTrendResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableWebTrendResponse(val *WebTrendResponse) *NullableWebTrendResponse {
	return &NullableWebTrendResponse{value: val, isSet: true}
}

func (v NullableWebTrendResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableWebTrendResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
