/*
Pago API

Personal finance tracking API. All /api/_* endpoints require either a session cookie (browser) or an Authorization: Bearer <token> header (machine clients).

API version: 1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package pago

import (
	"encoding/json"
)

// checks if the WebTransactionsResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &WebTransactionsResponse{}

// WebTransactionsResponse struct for WebTransactionsResponse
type WebTransactionsResponse struct {
	Count        *int32              `json:"count,omitempty"`
	Transactions []WebTransactionDTO `json:"transactions,omitempty"`
}

// NewWebTransactionsResponse instantiates a new WebTransactionsResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewWebTransactionsResponse() *WebTransactionsResponse {
	this := WebTransactionsResponse{}
	return &this
}

// NewWebTransactionsResponseWithDefaults instantiates a new WebTransactionsResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewWebTransactionsResponseWithDefaults() *WebTransactionsResponse {
	this := WebTransactionsResponse{}
	return &this
}

// GetCount returns the Count field value if set, zero value otherwise.
func (o *WebTransactionsResponse) GetCount() int32 {
	if o == nil || IsNil(o.Count) {
		var ret int32
		return ret
	}
	return *o.Count
}

// GetCountOk returns a tuple with the Count field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *WebTransactionsResponse) GetCountOk() (*int32, bool) {
	if o == nil || IsNil(o.Count) {
		return nil, false
	}
	return o.Count, true
}

// HasCount returns a boolean if a field has been set.
func (o *WebTransactionsResponse) HasCount() bool {
	if o != nil && !IsNil(o.Count) {
		return true
	}

	return false
}

// SetCount gets a reference to the given int32 and assigns it to the Count field.
func (o *WebTransactionsResponse) SetCount(v int32) {
	o.Count = &v
}

// GetTransactions returns the Transactions field value if set, zero value otherwise.
func (o *WebTransactionsResponse) GetTransactions() []WebTransactionDTO {
	if o == nil || IsNil(o.Transactions) {
		var ret []WebTransactionDTO
		return ret
	}
	return o.Transactions
}

// GetTransactionsOk returns a tuple with the Transactions field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *WebTransactionsResponse) GetTransactionsOk() ([]WebTransactionDTO, bool) {
	if o == nil || IsNil(o.Transactions) {
		return nil, false
	}
	return o.Transactions, true
}

// HasTransactions returns a boolean if a field has been set.
func (o *WebTransactionsResponse) HasTransactions() bool {
	if o != nil && !IsNil(o.Transactions) {
		return true
	}

	return false
}

// SetTransactions gets a reference to the given []WebTransactionDTO and assigns it to the Transactions field.
func (o *WebTransactionsResponse) SetTransactions(v []WebTransactionDTO) {
	o.Transactions = v
}

func (o WebTransactionsResponse) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o WebTransactionsResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Count) {
		toSerialize["count"] = o.Count
	}
	if !IsNil(o.Transactions) {
		toSerialize["transactions"] = o.Transactions
	}
	return toSerialize, nil
}

type NullableWebTransactionsResponse struct {
	value *WebTransactionsResponse
	isSet bool
}

func (v NullableWebTransactionsResponse) Get() *WebTransactionsResponse {
	return v.value
}

func (v *NullableWebTransactionsResponse) Set(val *WebTransactionsResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableWebTransactionsResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableWebTransactionsResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableWebTransactionsResponse(val *WebTransactionsResponse) *NullableWebTransactionsResponse {
	return &NullableWebTransactionsResponse{value: val, isSet: true}
}

func (v NullableWebTransactionsResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableWebTransactionsResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
