/*
Pago API

Personal finance tracking API. All /api/_* endpoints require either a session cookie (browser) or an Authorization: Bearer <token> header (machine clients).

API version: 1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package pago

import (
	"encoding/json"
)

// checks if the WebStatsResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &WebStatsResponse{}

// WebStatsResponse struct for WebStatsResponse
type WebStatsResponse struct {
	Balance           *float32 `json:"balance,omitempty"`
	TotalExpenses     *float32 `json:"totalExpenses,omitempty"`
	TotalIncome       *float32 `json:"totalIncome,omitempty"`
	TotalTransactions *int32   `json:"totalTransactions,omitempty"`
}

// NewWebStatsResponse instantiates a new WebStatsResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewWebStatsResponse() *WebStatsResponse {
	this := WebStatsResponse{}
	return &this
}

// NewWebStatsResponseWithDefaults instantiates a new WebStatsResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewWebStatsResponseWithDefaults() *WebStatsResponse {
	this := WebStatsResponse{}
	return &this
}

// GetBalance returns the Balance field value if set, zero value otherwise.
func (o *WebStatsResponse) GetBalance() float32 {
	if o == nil || IsNil(o.Balance) {
		var ret float32
		return ret
	}
	return *o.Balance
}

// GetBalanceOk returns a tuple with the Balance field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *WebStatsResponse) GetBalanceOk() (*float32, bool) {
	if o == nil || IsNil(o.Balance) {
		return nil, false
	}
	return o.Balance, true
}

// HasBalance returns a boolean if a field has been set.
func (o *WebStatsResponse) HasBalance() bool {
	if o != nil && !IsNil(o.Balance) {
		return true
	}

	return false
}

// SetBalance gets a reference to the given float32 and assigns it to the Balance field.
func (o *WebStatsResponse) SetBalance(v float32) {
	o.Balance = &v
}

// GetTotalExpenses returns the TotalExpenses field value if set, zero value otherwise.
func (o *WebStatsResponse) GetTotalExpenses() float32 {
	if o == nil || IsNil(o.TotalExpenses) {
		var ret float32
		return ret
	}
	return *o.TotalExpenses
}

// GetTotalExpensesOk returns a tuple with the TotalExpenses field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *WebStatsResponse) GetTotalExpensesOk() (*float32, bool) {
	if o == nil || IsNil(o.TotalExpenses) {
		return nil, false
	}
	return o.TotalExpenses, true
}

// HasTotalExpenses returns a boolean if a field has been set.
func (o *WebStatsResponse) HasTotalExpenses() bool {
	if o != nil && !IsNil(o.TotalExpenses) {
		return true
	}

	return false
}

// SetTotalExpenses gets a reference to the given float32 and assigns it to the TotalExpenses field.
func (o *WebStatsResponse) SetTotalExpenses(v float32) {
	o.TotalExpenses = &v
}

// GetTotalIncome returns the TotalIncome field value if set, zero value otherwise.
func (o *WebStatsResponse) GetTotalIncome() float32 {
	if o == nil || IsNil(o.TotalIncome) {
		var ret float32
		return ret
	}
	return *o.TotalIncome
}

// GetTotalIncomeOk returns a tuple with the TotalIncome field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *WebStatsResponse) GetTotalIncomeOk() (*float32, bool) {
	if o == nil || IsNil(o.TotalIncome) {
		return nil, false
	}
	return o.TotalIncome, true
}

// HasTotalIncome returns a boolean if a field has been set.
func (o *WebStatsResponse) HasTotalIncome() bool {
	if o != nil && !IsNil(o.TotalIncome) {
		return true
	}

	return false
}

// SetTotalIncome gets a reference to the given float32 and assigns it to the TotalIncome field.
func (o *WebStatsResponse) SetTotalIncome(v float32) {
	o.TotalIncome = &v
}

// GetTotalTransactions returns the TotalTransactions field value if set, zero value otherwise.
func (o *WebStatsResponse) GetTotalTransactions() int32 {
	if o == nil || IsNil(o.TotalTransactions) {
		var ret int32
		return ret
	}
	return *o.TotalTransactions
}

// GetTotalTransactionsOk returns a tuple with the TotalTransactions field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *WebStatsResponse) GetTotalTransactionsOk() (*int32, bool) {
	if o == nil || IsNil(o.TotalTransactions) {
		return nil, false
	}
	return o.TotalTransactions, true
}

// HasTotalTransactions returns a boolean if a field has been set.
func (o *WebStatsResponse) HasTotalTransactions() bool {
	if o != nil && !IsNil(o.TotalTransactions) {
		return true
	}

	return false
}

// SetTotalTransactions gets a reference to the given int32 and assigns it to the TotalTransactions field.
func (o *WebStatsResponse) SetTotalTransactions(v int32) {
	o.TotalTransactions = &v
}

func (o WebStatsResponse) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o WebStatsResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Balance) {
		toSerialize["balance"] = o.Balance
	}
	if !IsNil(o.TotalExpenses) {
		toSerialize["totalExpenses"] = o.TotalExpenses
	}
	if !IsNil(o.TotalIncome) {
		toSerialize["totalIncome"] = o.TotalIncome
	}
	if !IsNil(o.TotalTransactions) {
		toSerialize["totalTransactions"] = o.TotalTransactions
	}
	return toSerialize, nil
}

type NullableWebStatsResponse struct {
	value *WebStatsResponse
	isSet bool
}

func (v NullableWebStatsResponse) Get() *WebStatsResponse {
	return v.value
}

func (v *NullableWebStatsResponse) Set(val *WebStatsResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableWebStatsResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableWebStatsResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableWebStatsResponse(val *WebStatsResponse) *NullableWebStatsResponse {
	return &NullableWebStatsResponse{value: val, isSet: true}
}

func (v NullableWebStatsResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableWebStatsResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
