/*
Pago API

Personal finance tracking API. All /api/_* endpoints require either a session cookie (browser) or an Authorization: Bearer <token> header (machine clients).

API version: 1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package pago

import (
	"encoding/json"
)

// checks if the WebDeleteTransactionRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &WebDeleteTransactionRequest{}

// WebDeleteTransactionRequest struct for WebDeleteTransactionRequest
type WebDeleteTransactionRequest struct {
	Id *int32 `json:"id,omitempty"`
}

// NewWebDeleteTransactionRequest instantiates a new WebDeleteTransactionRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewWebDeleteTransactionRequest() *WebDeleteTransactionRequest {
	this := WebDeleteTransactionRequest{}
	return &this
}

// NewWebDeleteTransactionRequestWithDefaults instantiates a new WebDeleteTransactionRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewWebDeleteTransactionRequestWithDefaults() *WebDeleteTransactionRequest {
	this := WebDeleteTransactionRequest{}
	return &this
}

// GetId returns the Id field value if set, zero value otherwise.
func (o *WebDeleteTransactionRequest) GetId() int32 {
	if o == nil || IsNil(o.Id) {
		var ret int32
		return ret
	}
	return *o.Id
}

// GetIdOk returns a tuple with the Id field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *WebDeleteTransactionRequest) GetIdOk() (*int32, bool) {
	if o == nil || IsNil(o.Id) {
		return nil, false
	}
	return o.Id, true
}

// HasId returns a boolean if a field has been set.
func (o *WebDeleteTransactionRequest) HasId() bool {
	if o != nil && !IsNil(o.Id) {
		return true
	}

	return false
}

// SetId gets a reference to the given int32 and assigns it to the Id field.
func (o *WebDeleteTransactionRequest) SetId(v int32) {
	o.Id = &v
}

func (o WebDeleteTransactionRequest) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o WebDeleteTransactionRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Id) {
		toSerialize["id"] = o.Id
	}
	return toSerialize, nil
}

type NullableWebDeleteTransactionRequest struct {
	value *WebDeleteTransactionRequest
	isSet bool
}

func (v NullableWebDeleteTransactionRequest) Get() *WebDeleteTransactionRequest {
	return v.value
}

func (v *NullableWebDeleteTransactionRequest) Set(val *WebDeleteTransactionRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableWebDeleteTransactionRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableWebDeleteTransactionRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableWebDeleteTransactionRequest(val *WebDeleteTransactionRequest) *NullableWebDeleteTransactionRequest {
	return &NullableWebDeleteTransactionRequest{value: val, isSet: true}
}

func (v NullableWebDeleteTransactionRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableWebDeleteTransactionRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
