/*
Pago API

Personal finance tracking API. All /api/_* endpoints require either a session cookie (browser) or an Authorization: Bearer <token> header (machine clients).

API version: 1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package pago

import (
	"encoding/json"
)

// checks if the WebMonthPoint type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &WebMonthPoint{}

// WebMonthPoint struct for WebMonthPoint
type WebMonthPoint struct {
	Balance *float32 `json:"balance,omitempty"`
	Expense *float32 `json:"expense,omitempty"`
	Income  *float32 `json:"income,omitempty"`
	Month   *string  `json:"month,omitempty"`
}

// NewWebMonthPoint instantiates a new WebMonthPoint object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewWebMonthPoint() *WebMonthPoint {
	this := WebMonthPoint{}
	return &this
}

// NewWebMonthPointWithDefaults instantiates a new WebMonthPoint object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewWebMonthPointWithDefaults() *WebMonthPoint {
	this := WebMonthPoint{}
	return &this
}

// GetBalance returns the Balance field value if set, zero value otherwise.
func (o *WebMonthPoint) GetBalance() float32 {
	if o == nil || IsNil(o.Balance) {
		var ret float32
		return ret
	}
	return *o.Balance
}

// GetBalanceOk returns a tuple with the Balance field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *WebMonthPoint) GetBalanceOk() (*float32, bool) {
	if o == nil || IsNil(o.Balance) {
		return nil, false
	}
	return o.Balance, true
}

// HasBalance returns a boolean if a field has been set.
func (o *WebMonthPoint) HasBalance() bool {
	if o != nil && !IsNil(o.Balance) {
		return true
	}

	return false
}

// SetBalance gets a reference to the given float32 and assigns it to the Balance field.
func (o *WebMonthPoint) SetBalance(v float32) {
	o.Balance = &v
}

// GetExpense returns the Expense field value if set, zero value otherwise.
func (o *WebMonthPoint) GetExpense() float32 {
	if o == nil || IsNil(o.Expense) {
		var ret float32
		return ret
	}
	return *o.Expense
}

// GetExpenseOk returns a tuple with the Expense field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *WebMonthPoint) GetExpenseOk() (*float32, bool) {
	if o == nil || IsNil(o.Expense) {
		return nil, false
	}
	return o.Expense, true
}

// HasExpense returns a boolean if a field has been set.
func (o *WebMonthPoint) HasExpense() bool {
	if o != nil && !IsNil(o.Expense) {
		return true
	}

	return false
}

// SetExpense gets a reference to the given float32 and assigns it to the Expense field.
func (o *WebMonthPoint) SetExpense(v float32) {
	o.Expense = &v
}

// GetIncome returns the Income field value if set, zero value otherwise.
func (o *WebMonthPoint) GetIncome() float32 {
	if o == nil || IsNil(o.Income) {
		var ret float32
		return ret
	}
	return *o.Income
}

// GetIncomeOk returns a tuple with the Income field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *WebMonthPoint) GetIncomeOk() (*float32, bool) {
	if o == nil || IsNil(o.Income) {
		return nil, false
	}
	return o.Income, true
}

// HasIncome returns a boolean if a field has been set.
func (o *WebMonthPoint) HasIncome() bool {
	if o != nil && !IsNil(o.Income) {
		return true
	}

	return false
}

// SetIncome gets a reference to the given float32 and assigns it to the Income field.
func (o *WebMonthPoint) SetIncome(v float32) {
	o.Income = &v
}

// GetMonth returns the Month field value if set, zero value otherwise.
func (o *WebMonthPoint) GetMonth() string {
	if o == nil || IsNil(o.Month) {
		var ret string
		return ret
	}
	return *o.Month
}

// GetMonthOk returns a tuple with the Month field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *WebMonthPoint) GetMonthOk() (*string, bool) {
	if o == nil || IsNil(o.Month) {
		return nil, false
	}
	return o.Month, true
}

// HasMonth returns a boolean if a field has been set.
func (o *WebMonthPoint) HasMonth() bool {
	if o != nil && !IsNil(o.Month) {
		return true
	}

	return false
}

// SetMonth gets a reference to the given string and assigns it to the Month field.
func (o *WebMonthPoint) SetMonth(v string) {
	o.Month = &v
}

func (o WebMonthPoint) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o WebMonthPoint) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Balance) {
		toSerialize["balance"] = o.Balance
	}
	if !IsNil(o.Expense) {
		toSerialize["expense"] = o.Expense
	}
	if !IsNil(o.Income) {
		toSerialize["income"] = o.Income
	}
	if !IsNil(o.Month) {
		toSerialize["month"] = o.Month
	}
	return toSerialize, nil
}

type NullableWebMonthPoint struct {
	value *WebMonthPoint
	isSet bool
}

func (v NullableWebMonthPoint) Get() *WebMonthPoint {
	return v.value
}

func (v *NullableWebMonthPoint) Set(val *WebMonthPoint) {
	v.value = val
	v.isSet = true
}

func (v NullableWebMonthPoint) IsSet() bool {
	return v.isSet
}

func (v *NullableWebMonthPoint) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableWebMonthPoint(val *WebMonthPoint) *NullableWebMonthPoint {
	return &NullableWebMonthPoint{value: val, isSet: true}
}

func (v NullableWebMonthPoint) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableWebMonthPoint) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
