/*
Pago API

Personal finance tracking API. All /api/_* endpoints require either a session cookie (browser) or an Authorization: Bearer <token> header (machine clients).

API version: 1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package pago

import (
	"encoding/json"
)

// checks if the WebMonthlyAnalyticsResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &WebMonthlyAnalyticsResponse{}

// WebMonthlyAnalyticsResponse struct for WebMonthlyAnalyticsResponse
type WebMonthlyAnalyticsResponse struct {
	Balance       *float32              `json:"balance,omitempty"`
	ByCategory    *WebCategoryBreakdown `json:"byCategory,omitempty"`
	Month         *string               `json:"month,omitempty"`
	TotalExpenses *float32              `json:"totalExpenses,omitempty"`
	TotalIncome   *float32              `json:"totalIncome,omitempty"`
}

// NewWebMonthlyAnalyticsResponse instantiates a new WebMonthlyAnalyticsResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewWebMonthlyAnalyticsResponse() *WebMonthlyAnalyticsResponse {
	this := WebMonthlyAnalyticsResponse{}
	return &this
}

// NewWebMonthlyAnalyticsResponseWithDefaults instantiates a new WebMonthlyAnalyticsResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewWebMonthlyAnalyticsResponseWithDefaults() *WebMonthlyAnalyticsResponse {
	this := WebMonthlyAnalyticsResponse{}
	return &this
}

// GetBalance returns the Balance field value if set, zero value otherwise.
func (o *WebMonthlyAnalyticsResponse) GetBalance() float32 {
	if o == nil || IsNil(o.Balance) {
		var ret float32
		return ret
	}
	return *o.Balance
}

// GetBalanceOk returns a tuple with the Balance field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *WebMonthlyAnalyticsResponse) GetBalanceOk() (*float32, bool) {
	if o == nil || IsNil(o.Balance) {
		return nil, false
	}
	return o.Balance, true
}

// HasBalance returns a boolean if a field has been set.
func (o *WebMonthlyAnalyticsResponse) HasBalance() bool {
	if o != nil && !IsNil(o.Balance) {
		return true
	}

	return false
}

// SetBalance gets a reference to the given float32 and assigns it to the Balance field.
func (o *WebMonthlyAnalyticsResponse) SetBalance(v float32) {
	o.Balance = &v
}

// GetByCategory returns the ByCategory field value if set, zero value otherwise.
func (o *WebMonthlyAnalyticsResponse) GetByCategory() WebCategoryBreakdown {
	if o == nil || IsNil(o.ByCategory) {
		var ret WebCategoryBreakdown
		return ret
	}
	return *o.ByCategory
}

// GetByCategoryOk returns a tuple with the ByCategory field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *WebMonthlyAnalyticsResponse) GetByCategoryOk() (*WebCategoryBreakdown, bool) {
	if o == nil || IsNil(o.ByCategory) {
		return nil, false
	}
	return o.ByCategory, true
}

// HasByCategory returns a boolean if a field has been set.
func (o *WebMonthlyAnalyticsResponse) HasByCategory() bool {
	if o != nil && !IsNil(o.ByCategory) {
		return true
	}

	return false
}

// SetByCategory gets a reference to the given WebCategoryBreakdown and assigns it to the ByCategory field.
func (o *WebMonthlyAnalyticsResponse) SetByCategory(v WebCategoryBreakdown) {
	o.ByCategory = &v
}

// GetMonth returns the Month field value if set, zero value otherwise.
func (o *WebMonthlyAnalyticsResponse) GetMonth() string {
	if o == nil || IsNil(o.Month) {
		var ret string
		return ret
	}
	return *o.Month
}

// GetMonthOk returns a tuple with the Month field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *WebMonthlyAnalyticsResponse) GetMonthOk() (*string, bool) {
	if o == nil || IsNil(o.Month) {
		return nil, false
	}
	return o.Month, true
}

// HasMonth returns a boolean if a field has been set.
func (o *WebMonthlyAnalyticsResponse) HasMonth() bool {
	if o != nil && !IsNil(o.Month) {
		return true
	}

	return false
}

// SetMonth gets a reference to the given string and assigns it to the Month field.
func (o *WebMonthlyAnalyticsResponse) SetMonth(v string) {
	o.Month = &v
}

// GetTotalExpenses returns the TotalExpenses field value if set, zero value otherwise.
func (o *WebMonthlyAnalyticsResponse) GetTotalExpenses() float32 {
	if o == nil || IsNil(o.TotalExpenses) {
		var ret float32
		return ret
	}
	return *o.TotalExpenses
}

// GetTotalExpensesOk returns a tuple with the TotalExpenses field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *WebMonthlyAnalyticsResponse) GetTotalExpensesOk() (*float32, bool) {
	if o == nil || IsNil(o.TotalExpenses) {
		return nil, false
	}
	return o.TotalExpenses, true
}

// HasTotalExpenses returns a boolean if a field has been set.
func (o *WebMonthlyAnalyticsResponse) HasTotalExpenses() bool {
	if o != nil && !IsNil(o.TotalExpenses) {
		return true
	}

	return false
}

// SetTotalExpenses gets a reference to the given float32 and assigns it to the TotalExpenses field.
func (o *WebMonthlyAnalyticsResponse) SetTotalExpenses(v float32) {
	o.TotalExpenses = &v
}

// GetTotalIncome returns the TotalIncome field value if set, zero value otherwise.
func (o *WebMonthlyAnalyticsResponse) GetTotalIncome() float32 {
	if o == nil || IsNil(o.TotalIncome) {
		var ret float32
		return ret
	}
	return *o.TotalIncome
}

// GetTotalIncomeOk returns a tuple with the TotalIncome field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *WebMonthlyAnalyticsResponse) GetTotalIncomeOk() (*float32, bool) {
	if o == nil || IsNil(o.TotalIncome) {
		return nil, false
	}
	return o.TotalIncome, true
}

// HasTotalIncome returns a boolean if a field has been set.
func (o *WebMonthlyAnalyticsResponse) HasTotalIncome() bool {
	if o != nil && !IsNil(o.TotalIncome) {
		return true
	}

	return false
}

// SetTotalIncome gets a reference to the given float32 and assigns it to the TotalIncome field.
func (o *WebMonthlyAnalyticsResponse) SetTotalIncome(v float32) {
	o.TotalIncome = &v
}

func (o WebMonthlyAnalyticsResponse) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o WebMonthlyAnalyticsResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Balance) {
		toSerialize["balance"] = o.Balance
	}
	if !IsNil(o.ByCategory) {
		toSerialize["byCategory"] = o.ByCategory
	}
	if !IsNil(o.Month) {
		toSerialize["month"] = o.Month
	}
	if !IsNil(o.TotalExpenses) {
		toSerialize["totalExpenses"] = o.TotalExpenses
	}
	if !IsNil(o.TotalIncome) {
		toSerialize["totalIncome"] = o.TotalIncome
	}
	return toSerialize, nil
}

type NullableWebMonthlyAnalyticsResponse struct {
	value *WebMonthlyAnalyticsResponse
	isSet bool
}

func (v NullableWebMonthlyAnalyticsResponse) Get() *WebMonthlyAnalyticsResponse {
	return v.value
}

func (v *NullableWebMonthlyAnalyticsResponse) Set(val *WebMonthlyAnalyticsResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableWebMonthlyAnalyticsResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableWebMonthlyAnalyticsResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableWebMonthlyAnalyticsResponse(val *WebMonthlyAnalyticsResponse) *NullableWebMonthlyAnalyticsResponse {
	return &NullableWebMonthlyAnalyticsResponse{value: val, isSet: true}
}

func (v NullableWebMonthlyAnalyticsResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableWebMonthlyAnalyticsResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
