/*
Pago API

Personal finance tracking API. All /api/_* endpoints require either a session cookie (browser) or an Authorization: Bearer <token> header (machine clients).

API version: 1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package pago

import (
	"encoding/json"
)

// checks if the WebSearchTransactionsRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &WebSearchTransactionsRequest{}

// WebSearchTransactionsRequest struct for WebSearchTransactionsRequest
type WebSearchTransactionsRequest struct {
	AmountMax *float32 `json:"amountMax,omitempty"`
	AmountMin *float32 `json:"amountMin,omitempty"`
	Category  *string  `json:"category,omitempty"`
	DateFrom  *string  `json:"dateFrom,omitempty"`
	DateTo    *string  `json:"dateTo,omitempty"`
	Limit     *int32   `json:"limit,omitempty"`
	Offset    *int32   `json:"offset,omitempty"`
	Query     *string  `json:"query,omitempty"`
	Type      *string  `json:"type,omitempty"`
}

// NewWebSearchTransactionsRequest instantiates a new WebSearchTransactionsRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewWebSearchTransactionsRequest() *WebSearchTransactionsRequest {
	this := WebSearchTransactionsRequest{}
	return &this
}

// NewWebSearchTransactionsRequestWithDefaults instantiates a new WebSearchTransactionsRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewWebSearchTransactionsRequestWithDefaults() *WebSearchTransactionsRequest {
	this := WebSearchTransactionsRequest{}
	return &this
}

// GetAmountMax returns the AmountMax field value if set, zero value otherwise.
func (o *WebSearchTransactionsRequest) GetAmountMax() float32 {
	if o == nil || IsNil(o.AmountMax) {
		var ret float32
		return ret
	}
	return *o.AmountMax
}

// GetAmountMaxOk returns a tuple with the AmountMax field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *WebSearchTransactionsRequest) GetAmountMaxOk() (*float32, bool) {
	if o == nil || IsNil(o.AmountMax) {
		return nil, false
	}
	return o.AmountMax, true
}

// HasAmountMax returns a boolean if a field has been set.
func (o *WebSearchTransactionsRequest) HasAmountMax() bool {
	if o != nil && !IsNil(o.AmountMax) {
		return true
	}

	return false
}

// SetAmountMax gets a reference to the given float32 and assigns it to the AmountMax field.
func (o *WebSearchTransactionsRequest) SetAmountMax(v float32) {
	o.AmountMax = &v
}

// GetAmountMin returns the AmountMin field value if set, zero value otherwise.
func (o *WebSearchTransactionsRequest) GetAmountMin() float32 {
	if o == nil || IsNil(o.AmountMin) {
		var ret float32
		return ret
	}
	return *o.AmountMin
}

// GetAmountMinOk returns a tuple with the AmountMin field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *WebSearchTransactionsRequest) GetAmountMinOk() (*float32, bool) {
	if o == nil || IsNil(o.AmountMin) {
		return nil, false
	}
	return o.AmountMin, true
}

// HasAmountMin returns a boolean if a field has been set.
func (o *WebSearchTransactionsRequest) HasAmountMin() bool {
	if o != nil && !IsNil(o.AmountMin) {
		return true
	}

	return false
}

// SetAmountMin gets a reference to the given float32 and assigns it to the AmountMin field.
func (o *WebSearchTransactionsRequest) SetAmountMin(v float32) {
	o.AmountMin = &v
}

// GetCategory returns the Category field value if set, zero value otherwise.
func (o *WebSearchTransactionsRequest) GetCategory() string {
	if o == nil || IsNil(o.Category) {
		var ret string
		return ret
	}
	return *o.Category
}

// GetCategoryOk returns a tuple with the Category field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *WebSearchTransactionsRequest) GetCategoryOk() (*string, bool) {
	if o == nil || IsNil(o.Category) {
		return nil, false
	}
	return o.Category, true
}

// HasCategory returns a boolean if a field has been set.
func (o *WebSearchTransactionsRequest) HasCategory() bool {
	if o != nil && !IsNil(o.Category) {
		return true
	}

	return false
}

// SetCategory gets a reference to the given string and assigns it to the Category field.
func (o *WebSearchTransactionsRequest) SetCategory(v string) {
	o.Category = &v
}

// GetDateFrom returns the DateFrom field value if set, zero value otherwise.
func (o *WebSearchTransactionsRequest) GetDateFrom() string {
	if o == nil || IsNil(o.DateFrom) {
		var ret string
		return ret
	}
	return *o.DateFrom
}

// GetDateFromOk returns a tuple with the DateFrom field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *WebSearchTransactionsRequest) GetDateFromOk() (*string, bool) {
	if o == nil || IsNil(o.DateFrom) {
		return nil, false
	}
	return o.DateFrom, true
}

// HasDateFrom returns a boolean if a field has been set.
func (o *WebSearchTransactionsRequest) HasDateFrom() bool {
	if o != nil && !IsNil(o.DateFrom) {
		return true
	}

	return false
}

// SetDateFrom gets a reference to the given string and assigns it to the DateFrom field.
func (o *WebSearchTransactionsRequest) SetDateFrom(v string) {
	o.DateFrom = &v
}

// GetDateTo returns the DateTo field value if set, zero value otherwise.
func (o *WebSearchTransactionsRequest) GetDateTo() string {
	if o == nil || IsNil(o.DateTo) {
		var ret string
		return ret
	}
	return *o.DateTo
}

// GetDateToOk returns a tuple with the DateTo field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *WebSearchTransactionsRequest) GetDateToOk() (*string, bool) {
	if o == nil || IsNil(o.DateTo) {
		return nil, false
	}
	return o.DateTo, true
}

// HasDateTo returns a boolean if a field has been set.
func (o *WebSearchTransactionsRequest) HasDateTo() bool {
	if o != nil && !IsNil(o.DateTo) {
		return true
	}

	return false
}

// SetDateTo gets a reference to the given string and assigns it to the DateTo field.
func (o *WebSearchTransactionsRequest) SetDateTo(v string) {
	o.DateTo = &v
}

// GetLimit returns the Limit field value if set, zero value otherwise.
func (o *WebSearchTransactionsRequest) GetLimit() int32 {
	if o == nil || IsNil(o.Limit) {
		var ret int32
		return ret
	}
	return *o.Limit
}

// GetLimitOk returns a tuple with the Limit field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *WebSearchTransactionsRequest) GetLimitOk() (*int32, bool) {
	if o == nil || IsNil(o.Limit) {
		return nil, false
	}
	return o.Limit, true
}

// HasLimit returns a boolean if a field has been set.
func (o *WebSearchTransactionsRequest) HasLimit() bool {
	if o != nil && !IsNil(o.Limit) {
		return true
	}

	return false
}

// SetLimit gets a reference to the given int32 and assigns it to the Limit field.
func (o *WebSearchTransactionsRequest) SetLimit(v int32) {
	o.Limit = &v
}

// GetOffset returns the Offset field value if set, zero value otherwise.
func (o *WebSearchTransactionsRequest) GetOffset() int32 {
	if o == nil || IsNil(o.Offset) {
		var ret int32
		return ret
	}
	return *o.Offset
}

// GetOffsetOk returns a tuple with the Offset field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *WebSearchTransactionsRequest) GetOffsetOk() (*int32, bool) {
	if o == nil || IsNil(o.Offset) {
		return nil, false
	}
	return o.Offset, true
}

// HasOffset returns a boolean if a field has been set.
func (o *WebSearchTransactionsRequest) HasOffset() bool {
	if o != nil && !IsNil(o.Offset) {
		return true
	}

	return false
}

// SetOffset gets a reference to the given int32 and assigns it to the Offset field.
func (o *WebSearchTransactionsRequest) SetOffset(v int32) {
	o.Offset = &v
}

// GetQuery returns the Query field value if set, zero value otherwise.
func (o *WebSearchTransactionsRequest) GetQuery() string {
	if o == nil || IsNil(o.Query) {
		var ret string
		return ret
	}
	return *o.Query
}

// GetQueryOk returns a tuple with the Query field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *WebSearchTransactionsRequest) GetQueryOk() (*string, bool) {
	if o == nil || IsNil(o.Query) {
		return nil, false
	}
	return o.Query, true
}

// HasQuery returns a boolean if a field has been set.
func (o *WebSearchTransactionsRequest) HasQuery() bool {
	if o != nil && !IsNil(o.Query) {
		return true
	}

	return false
}

// SetQuery gets a reference to the given string and assigns it to the Query field.
func (o *WebSearchTransactionsRequest) SetQuery(v string) {
	o.Query = &v
}

// GetType returns the Type field value if set, zero value otherwise.
func (o *WebSearchTransactionsRequest) GetType() string {
	if o == nil || IsNil(o.Type) {
		var ret string
		return ret
	}
	return *o.Type
}

// GetTypeOk returns a tuple with the Type field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *WebSearchTransactionsRequest) GetTypeOk() (*string, bool) {
	if o == nil || IsNil(o.Type) {
		return nil, false
	}
	return o.Type, true
}

// HasType returns a boolean if a field has been set.
func (o *WebSearchTransactionsRequest) HasType() bool {
	if o != nil && !IsNil(o.Type) {
		return true
	}

	return false
}

// SetType gets a reference to the given string and assigns it to the Type field.
func (o *WebSearchTransactionsRequest) SetType(v string) {
	o.Type = &v
}

func (o WebSearchTransactionsRequest) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o WebSearchTransactionsRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.AmountMax) {
		toSerialize["amountMax"] = o.AmountMax
	}
	if !IsNil(o.AmountMin) {
		toSerialize["amountMin"] = o.AmountMin
	}
	if !IsNil(o.Category) {
		toSerialize["category"] = o.Category
	}
	if !IsNil(o.DateFrom) {
		toSerialize["dateFrom"] = o.DateFrom
	}
	if !IsNil(o.DateTo) {
		toSerialize["dateTo"] = o.DateTo
	}
	if !IsNil(o.Limit) {
		toSerialize["limit"] = o.Limit
	}
	if !IsNil(o.Offset) {
		toSerialize["offset"] = o.Offset
	}
	if !IsNil(o.Query) {
		toSerialize["query"] = o.Query
	}
	if !IsNil(o.Type) {
		toSerialize["type"] = o.Type
	}
	return toSerialize, nil
}

type NullableWebSearchTransactionsRequest struct {
	value *WebSearchTransactionsRequest
	isSet bool
}

func (v NullableWebSearchTransactionsRequest) Get() *WebSearchTransactionsRequest {
	return v.value
}

func (v *NullableWebSearchTransactionsRequest) Set(val *WebSearchTransactionsRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableWebSearchTransactionsRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableWebSearchTransactionsRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableWebSearchTransactionsRequest(val *WebSearchTransactionsRequest) *NullableWebSearchTransactionsRequest {
	return &NullableWebSearchTransactionsRequest{value: val, isSet: true}
}

func (v NullableWebSearchTransactionsRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableWebSearchTransactionsRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
