/*
Pago API

Personal finance tracking API. All /api/_* endpoints require either a session cookie (browser) or an Authorization: Bearer <token> header (machine clients).

API version: 1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package pago

import (
	"encoding/json"
)

// checks if the WebBudgetUpsertRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &WebBudgetUpsertRequest{}

// WebBudgetUpsertRequest struct for WebBudgetUpsertRequest
type WebBudgetUpsertRequest struct {
	Amount *float32 `json:"amount,omitempty"`
}

// NewWebBudgetUpsertRequest instantiates a new WebBudgetUpsertRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewWebBudgetUpsertRequest() *WebBudgetUpsertRequest {
	this := WebBudgetUpsertRequest{}
	return &this
}

// NewWebBudgetUpsertRequestWithDefaults instantiates a new WebBudgetUpsertRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewWebBudgetUpsertRequestWithDefaults() *WebBudgetUpsertRequest {
	this := WebBudgetUpsertRequest{}
	return &this
}

// GetAmount returns the Amount field value if set, zero value otherwise.
func (o *WebBudgetUpsertRequest) GetAmount() float32 {
	if o == nil || IsNil(o.Amount) {
		var ret float32
		return ret
	}
	return *o.Amount
}

// GetAmountOk returns a tuple with the Amount field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *WebBudgetUpsertRequest) GetAmountOk() (*float32, bool) {
	if o == nil || IsNil(o.Amount) {
		return nil, false
	}
	return o.Amount, true
}

// HasAmount returns a boolean if a field has been set.
func (o *WebBudgetUpsertRequest) HasAmount() bool {
	if o != nil && !IsNil(o.Amount) {
		return true
	}

	return false
}

// SetAmount gets a reference to the given float32 and assigns it to the Amount field.
func (o *WebBudgetUpsertRequest) SetAmount(v float32) {
	o.Amount = &v
}

func (o WebBudgetUpsertRequest) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o WebBudgetUpsertRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Amount) {
		toSerialize["amount"] = o.Amount
	}
	return toSerialize, nil
}

type NullableWebBudgetUpsertRequest struct {
	value *WebBudgetUpsertRequest
	isSet bool
}

func (v NullableWebBudgetUpsertRequest) Get() *WebBudgetUpsertRequest {
	return v.value
}

func (v *NullableWebBudgetUpsertRequest) Set(val *WebBudgetUpsertRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableWebBudgetUpsertRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableWebBudgetUpsertRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableWebBudgetUpsertRequest(val *WebBudgetUpsertRequest) *NullableWebBudgetUpsertRequest {
	return &NullableWebBudgetUpsertRequest{value: val, isSet: true}
}

func (v NullableWebBudgetUpsertRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableWebBudgetUpsertRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
