/*
Pago API

Personal finance tracking API. All /api/_* endpoints require either a session cookie (browser) or an Authorization: Bearer <token> header (machine clients).

API version: 1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package pago

import (
	"encoding/json"
)

// checks if the WebYearAnalyticsResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &WebYearAnalyticsResponse{}

// WebYearAnalyticsResponse struct for WebYearAnalyticsResponse
type WebYearAnalyticsResponse struct {
	Balance       *float32              `json:"balance,omitempty"`
	ByCategory    *WebCategoryBreakdown `json:"byCategory,omitempty"`
	ByMonth       []WebYearMonthEntry   `json:"byMonth,omitempty"`
	TotalExpenses *float32              `json:"totalExpenses,omitempty"`
	TotalIncome   *float32              `json:"totalIncome,omitempty"`
	Year          *int32                `json:"year,omitempty"`
}

// NewWebYearAnalyticsResponse instantiates a new WebYearAnalyticsResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewWebYearAnalyticsResponse() *WebYearAnalyticsResponse {
	this := WebYearAnalyticsResponse{}
	return &this
}

// NewWebYearAnalyticsResponseWithDefaults instantiates a new WebYearAnalyticsResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewWebYearAnalyticsResponseWithDefaults() *WebYearAnalyticsResponse {
	this := WebYearAnalyticsResponse{}
	return &this
}

// GetBalance returns the Balance field value if set, zero value otherwise.
func (o *WebYearAnalyticsResponse) GetBalance() float32 {
	if o == nil || IsNil(o.Balance) {
		var ret float32
		return ret
	}
	return *o.Balance
}

// GetBalanceOk returns a tuple with the Balance field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *WebYearAnalyticsResponse) GetBalanceOk() (*float32, bool) {
	if o == nil || IsNil(o.Balance) {
		return nil, false
	}
	return o.Balance, true
}

// HasBalance returns a boolean if a field has been set.
func (o *WebYearAnalyticsResponse) HasBalance() bool {
	if o != nil && !IsNil(o.Balance) {
		return true
	}

	return false
}

// SetBalance gets a reference to the given float32 and assigns it to the Balance field.
func (o *WebYearAnalyticsResponse) SetBalance(v float32) {
	o.Balance = &v
}

// GetByCategory returns the ByCategory field value if set, zero value otherwise.
func (o *WebYearAnalyticsResponse) GetByCategory() WebCategoryBreakdown {
	if o == nil || IsNil(o.ByCategory) {
		var ret WebCategoryBreakdown
		return ret
	}
	return *o.ByCategory
}

// GetByCategoryOk returns a tuple with the ByCategory field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *WebYearAnalyticsResponse) GetByCategoryOk() (*WebCategoryBreakdown, bool) {
	if o == nil || IsNil(o.ByCategory) {
		return nil, false
	}
	return o.ByCategory, true
}

// HasByCategory returns a boolean if a field has been set.
func (o *WebYearAnalyticsResponse) HasByCategory() bool {
	if o != nil && !IsNil(o.ByCategory) {
		return true
	}

	return false
}

// SetByCategory gets a reference to the given WebCategoryBreakdown and assigns it to the ByCategory field.
func (o *WebYearAnalyticsResponse) SetByCategory(v WebCategoryBreakdown) {
	o.ByCategory = &v
}

// GetByMonth returns the ByMonth field value if set, zero value otherwise.
func (o *WebYearAnalyticsResponse) GetByMonth() []WebYearMonthEntry {
	if o == nil || IsNil(o.ByMonth) {
		var ret []WebYearMonthEntry
		return ret
	}
	return o.ByMonth
}

// GetByMonthOk returns a tuple with the ByMonth field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *WebYearAnalyticsResponse) GetByMonthOk() ([]WebYearMonthEntry, bool) {
	if o == nil || IsNil(o.ByMonth) {
		return nil, false
	}
	return o.ByMonth, true
}

// HasByMonth returns a boolean if a field has been set.
func (o *WebYearAnalyticsResponse) HasByMonth() bool {
	if o != nil && !IsNil(o.ByMonth) {
		return true
	}

	return false
}

// SetByMonth gets a reference to the given []WebYearMonthEntry and assigns it to the ByMonth field.
func (o *WebYearAnalyticsResponse) SetByMonth(v []WebYearMonthEntry) {
	o.ByMonth = v
}

// GetTotalExpenses returns the TotalExpenses field value if set, zero value otherwise.
func (o *WebYearAnalyticsResponse) GetTotalExpenses() float32 {
	if o == nil || IsNil(o.TotalExpenses) {
		var ret float32
		return ret
	}
	return *o.TotalExpenses
}

// GetTotalExpensesOk returns a tuple with the TotalExpenses field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *WebYearAnalyticsResponse) GetTotalExpensesOk() (*float32, bool) {
	if o == nil || IsNil(o.TotalExpenses) {
		return nil, false
	}
	return o.TotalExpenses, true
}

// HasTotalExpenses returns a boolean if a field has been set.
func (o *WebYearAnalyticsResponse) HasTotalExpenses() bool {
	if o != nil && !IsNil(o.TotalExpenses) {
		return true
	}

	return false
}

// SetTotalExpenses gets a reference to the given float32 and assigns it to the TotalExpenses field.
func (o *WebYearAnalyticsResponse) SetTotalExpenses(v float32) {
	o.TotalExpenses = &v
}

// GetTotalIncome returns the TotalIncome field value if set, zero value otherwise.
func (o *WebYearAnalyticsResponse) GetTotalIncome() float32 {
	if o == nil || IsNil(o.TotalIncome) {
		var ret float32
		return ret
	}
	return *o.TotalIncome
}

// GetTotalIncomeOk returns a tuple with the TotalIncome field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *WebYearAnalyticsResponse) GetTotalIncomeOk() (*float32, bool) {
	if o == nil || IsNil(o.TotalIncome) {
		return nil, false
	}
	return o.TotalIncome, true
}

// HasTotalIncome returns a boolean if a field has been set.
func (o *WebYearAnalyticsResponse) HasTotalIncome() bool {
	if o != nil && !IsNil(o.TotalIncome) {
		return true
	}

	return false
}

// SetTotalIncome gets a reference to the given float32 and assigns it to the TotalIncome field.
func (o *WebYearAnalyticsResponse) SetTotalIncome(v float32) {
	o.TotalIncome = &v
}

// GetYear returns the Year field value if set, zero value otherwise.
func (o *WebYearAnalyticsResponse) GetYear() int32 {
	if o == nil || IsNil(o.Year) {
		var ret int32
		return ret
	}
	return *o.Year
}

// GetYearOk returns a tuple with the Year field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *WebYearAnalyticsResponse) GetYearOk() (*int32, bool) {
	if o == nil || IsNil(o.Year) {
		return nil, false
	}
	return o.Year, true
}

// HasYear returns a boolean if a field has been set.
func (o *WebYearAnalyticsResponse) HasYear() bool {
	if o != nil && !IsNil(o.Year) {
		return true
	}

	return false
}

// SetYear gets a reference to the given int32 and assigns it to the Year field.
func (o *WebYearAnalyticsResponse) SetYear(v int32) {
	o.Year = &v
}

func (o WebYearAnalyticsResponse) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o WebYearAnalyticsResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Balance) {
		toSerialize["balance"] = o.Balance
	}
	if !IsNil(o.ByCategory) {
		toSerialize["byCategory"] = o.ByCategory
	}
	if !IsNil(o.ByMonth) {
		toSerialize["byMonth"] = o.ByMonth
	}
	if !IsNil(o.TotalExpenses) {
		toSerialize["totalExpenses"] = o.TotalExpenses
	}
	if !IsNil(o.TotalIncome) {
		toSerialize["totalIncome"] = o.TotalIncome
	}
	if !IsNil(o.Year) {
		toSerialize["year"] = o.Year
	}
	return toSerialize, nil
}

type NullableWebYearAnalyticsResponse struct {
	value *WebYearAnalyticsResponse
	isSet bool
}

func (v NullableWebYearAnalyticsResponse) Get() *WebYearAnalyticsResponse {
	return v.value
}

func (v *NullableWebYearAnalyticsResponse) Set(val *WebYearAnalyticsResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableWebYearAnalyticsResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableWebYearAnalyticsResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableWebYearAnalyticsResponse(val *WebYearAnalyticsResponse) *NullableWebYearAnalyticsResponse {
	return &NullableWebYearAnalyticsResponse{value: val, isSet: true}
}

func (v NullableWebYearAnalyticsResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableWebYearAnalyticsResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
