/*
Pago API

Personal finance tracking API. All /api/_* endpoints require either a session cookie (browser) or an Authorization: Bearer <token> header (machine clients).

API version: 1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package pago

import (
	"encoding/json"
)

// checks if the WebErrorResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &WebErrorResponse{}

// WebErrorResponse struct for WebErrorResponse
type WebErrorResponse struct {
	Error *string `json:"error,omitempty"`
}

// NewWebErrorResponse instantiates a new WebErrorResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewWebErrorResponse() *WebErrorResponse {
	this := WebErrorResponse{}
	return &this
}

// NewWebErrorResponseWithDefaults instantiates a new WebErrorResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewWebErrorResponseWithDefaults() *WebErrorResponse {
	this := WebErrorResponse{}
	return &this
}

// GetError returns the Error field value if set, zero value otherwise.
func (o *WebErrorResponse) GetError() string {
	if o == nil || IsNil(o.Error) {
		var ret string
		return ret
	}
	return *o.Error
}

// GetErrorOk returns a tuple with the Error field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *WebErrorResponse) GetErrorOk() (*string, bool) {
	if o == nil || IsNil(o.Error) {
		return nil, false
	}
	return o.Error, true
}

// HasError returns a boolean if a field has been set.
func (o *WebErrorResponse) HasError() bool {
	if o != nil && !IsNil(o.Error) {
		return true
	}

	return false
}

// SetError gets a reference to the given string and assigns it to the Error field.
func (o *WebErrorResponse) SetError(v string) {
	o.Error = &v
}

func (o WebErrorResponse) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o WebErrorResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Error) {
		toSerialize["error"] = o.Error
	}
	return toSerialize, nil
}

type NullableWebErrorResponse struct {
	value *WebErrorResponse
	isSet bool
}

func (v NullableWebErrorResponse) Get() *WebErrorResponse {
	return v.value
}

func (v *NullableWebErrorResponse) Set(val *WebErrorResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableWebErrorResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableWebErrorResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableWebErrorResponse(val *WebErrorResponse) *NullableWebErrorResponse {
	return &NullableWebErrorResponse{value: val, isSet: true}
}

func (v NullableWebErrorResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableWebErrorResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
