/*
Pago API

Personal finance tracking API. All /api/_* endpoints require either a session cookie (browser) or an Authorization: Bearer <token> header (machine clients).

API version: 1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package pago

import (
	"encoding/json"
)

// checks if the WebYearMonthEntry type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &WebYearMonthEntry{}

// WebYearMonthEntry struct for WebYearMonthEntry
type WebYearMonthEntry struct {
	Balance *float32 `json:"balance,omitempty"`
	Expense *float32 `json:"expense,omitempty"`
	Income  *float32 `json:"income,omitempty"`
	Month   *int32   `json:"month,omitempty"`
}

// NewWebYearMonthEntry instantiates a new WebYearMonthEntry object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewWebYearMonthEntry() *WebYearMonthEntry {
	this := WebYearMonthEntry{}
	return &this
}

// NewWebYearMonthEntryWithDefaults instantiates a new WebYearMonthEntry object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewWebYearMonthEntryWithDefaults() *WebYearMonthEntry {
	this := WebYearMonthEntry{}
	return &this
}

// GetBalance returns the Balance field value if set, zero value otherwise.
func (o *WebYearMonthEntry) GetBalance() float32 {
	if o == nil || IsNil(o.Balance) {
		var ret float32
		return ret
	}
	return *o.Balance
}

// GetBalanceOk returns a tuple with the Balance field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *WebYearMonthEntry) GetBalanceOk() (*float32, bool) {
	if o == nil || IsNil(o.Balance) {
		return nil, false
	}
	return o.Balance, true
}

// HasBalance returns a boolean if a field has been set.
func (o *WebYearMonthEntry) HasBalance() bool {
	if o != nil && !IsNil(o.Balance) {
		return true
	}

	return false
}

// SetBalance gets a reference to the given float32 and assigns it to the Balance field.
func (o *WebYearMonthEntry) SetBalance(v float32) {
	o.Balance = &v
}

// GetExpense returns the Expense field value if set, zero value otherwise.
func (o *WebYearMonthEntry) GetExpense() float32 {
	if o == nil || IsNil(o.Expense) {
		var ret float32
		return ret
	}
	return *o.Expense
}

// GetExpenseOk returns a tuple with the Expense field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *WebYearMonthEntry) GetExpenseOk() (*float32, bool) {
	if o == nil || IsNil(o.Expense) {
		return nil, false
	}
	return o.Expense, true
}

// HasExpense returns a boolean if a field has been set.
func (o *WebYearMonthEntry) HasExpense() bool {
	if o != nil && !IsNil(o.Expense) {
		return true
	}

	return false
}

// SetExpense gets a reference to the given float32 and assigns it to the Expense field.
func (o *WebYearMonthEntry) SetExpense(v float32) {
	o.Expense = &v
}

// GetIncome returns the Income field value if set, zero value otherwise.
func (o *WebYearMonthEntry) GetIncome() float32 {
	if o == nil || IsNil(o.Income) {
		var ret float32
		return ret
	}
	return *o.Income
}

// GetIncomeOk returns a tuple with the Income field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *WebYearMonthEntry) GetIncomeOk() (*float32, bool) {
	if o == nil || IsNil(o.Income) {
		return nil, false
	}
	return o.Income, true
}

// HasIncome returns a boolean if a field has been set.
func (o *WebYearMonthEntry) HasIncome() bool {
	if o != nil && !IsNil(o.Income) {
		return true
	}

	return false
}

// SetIncome gets a reference to the given float32 and assigns it to the Income field.
func (o *WebYearMonthEntry) SetIncome(v float32) {
	o.Income = &v
}

// GetMonth returns the Month field value if set, zero value otherwise.
func (o *WebYearMonthEntry) GetMonth() int32 {
	if o == nil || IsNil(o.Month) {
		var ret int32
		return ret
	}
	return *o.Month
}

// GetMonthOk returns a tuple with the Month field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *WebYearMonthEntry) GetMonthOk() (*int32, bool) {
	if o == nil || IsNil(o.Month) {
		return nil, false
	}
	return o.Month, true
}

// HasMonth returns a boolean if a field has been set.
func (o *WebYearMonthEntry) HasMonth() bool {
	if o != nil && !IsNil(o.Month) {
		return true
	}

	return false
}

// SetMonth gets a reference to the given int32 and assigns it to the Month field.
func (o *WebYearMonthEntry) SetMonth(v int32) {
	o.Month = &v
}

func (o WebYearMonthEntry) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o WebYearMonthEntry) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Balance) {
		toSerialize["balance"] = o.Balance
	}
	if !IsNil(o.Expense) {
		toSerialize["expense"] = o.Expense
	}
	if !IsNil(o.Income) {
		toSerialize["income"] = o.Income
	}
	if !IsNil(o.Month) {
		toSerialize["month"] = o.Month
	}
	return toSerialize, nil
}

type NullableWebYearMonthEntry struct {
	value *WebYearMonthEntry
	isSet bool
}

func (v NullableWebYearMonthEntry) Get() *WebYearMonthEntry {
	return v.value
}

func (v *NullableWebYearMonthEntry) Set(val *WebYearMonthEntry) {
	v.value = val
	v.isSet = true
}

func (v NullableWebYearMonthEntry) IsSet() bool {
	return v.isSet
}

func (v *NullableWebYearMonthEntry) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableWebYearMonthEntry(val *WebYearMonthEntry) *NullableWebYearMonthEntry {
	return &NullableWebYearMonthEntry{value: val, isSet: true}
}

func (v NullableWebYearMonthEntry) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableWebYearMonthEntry) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
