/*
Pago API

Personal finance tracking API. All /api/_* endpoints require either a session cookie (browser) or an Authorization: Bearer <token> header (machine clients).

API version: 1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package pago

import (
	"encoding/json"
)

// checks if the WebCategoriesResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &WebCategoriesResponse{}

// WebCategoriesResponse struct for WebCategoriesResponse
type WebCategoriesResponse struct {
	Categories []string `json:"categories,omitempty"`
}

// NewWebCategoriesResponse instantiates a new WebCategoriesResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewWebCategoriesResponse() *WebCategoriesResponse {
	this := WebCategoriesResponse{}
	return &this
}

// NewWebCategoriesResponseWithDefaults instantiates a new WebCategoriesResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewWebCategoriesResponseWithDefaults() *WebCategoriesResponse {
	this := WebCategoriesResponse{}
	return &this
}

// GetCategories returns the Categories field value if set, zero value otherwise.
func (o *WebCategoriesResponse) GetCategories() []string {
	if o == nil || IsNil(o.Categories) {
		var ret []string
		return ret
	}
	return o.Categories
}

// GetCategoriesOk returns a tuple with the Categories field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *WebCategoriesResponse) GetCategoriesOk() ([]string, bool) {
	if o == nil || IsNil(o.Categories) {
		return nil, false
	}
	return o.Categories, true
}

// HasCategories returns a boolean if a field has been set.
func (o *WebCategoriesResponse) HasCategories() bool {
	if o != nil && !IsNil(o.Categories) {
		return true
	}

	return false
}

// SetCategories gets a reference to the given []string and assigns it to the Categories field.
func (o *WebCategoriesResponse) SetCategories(v []string) {
	o.Categories = v
}

func (o WebCategoriesResponse) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o WebCategoriesResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Categories) {
		toSerialize["categories"] = o.Categories
	}
	return toSerialize, nil
}

type NullableWebCategoriesResponse struct {
	value *WebCategoriesResponse
	isSet bool
}

func (v NullableWebCategoriesResponse) Get() *WebCategoriesResponse {
	return v.value
}

func (v *NullableWebCategoriesResponse) Set(val *WebCategoriesResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableWebCategoriesResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableWebCategoriesResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableWebCategoriesResponse(val *WebCategoriesResponse) *NullableWebCategoriesResponse {
	return &NullableWebCategoriesResponse{value: val, isSet: true}
}

func (v NullableWebCategoriesResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableWebCategoriesResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
