/*
Pago API

Personal finance tracking API. All /api/_* endpoints require either a session cookie (browser) or an Authorization: Bearer <token> header (machine clients).

API version: 1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package pago

import (
	"encoding/json"
)

// checks if the WebBudgetResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &WebBudgetResponse{}

// WebBudgetResponse struct for WebBudgetResponse
type WebBudgetResponse struct {
	Amount    *float32 `json:"amount,omitempty"`
	Currency  *string  `json:"currency,omitempty"`
	HasBudget *bool    `json:"hasBudget,omitempty"`
	Month     *string  `json:"month,omitempty"`
	Pct       *int32   `json:"pct,omitempty"`
	Spent     *float32 `json:"spent,omitempty"`
}

// NewWebBudgetResponse instantiates a new WebBudgetResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewWebBudgetResponse() *WebBudgetResponse {
	this := WebBudgetResponse{}
	return &this
}

// NewWebBudgetResponseWithDefaults instantiates a new WebBudgetResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewWebBudgetResponseWithDefaults() *WebBudgetResponse {
	this := WebBudgetResponse{}
	return &this
}

// GetAmount returns the Amount field value if set, zero value otherwise.
func (o *WebBudgetResponse) GetAmount() float32 {
	if o == nil || IsNil(o.Amount) {
		var ret float32
		return ret
	}
	return *o.Amount
}

// GetAmountOk returns a tuple with the Amount field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *WebBudgetResponse) GetAmountOk() (*float32, bool) {
	if o == nil || IsNil(o.Amount) {
		return nil, false
	}
	return o.Amount, true
}

// HasAmount returns a boolean if a field has been set.
func (o *WebBudgetResponse) HasAmount() bool {
	if o != nil && !IsNil(o.Amount) {
		return true
	}

	return false
}

// SetAmount gets a reference to the given float32 and assigns it to the Amount field.
func (o *WebBudgetResponse) SetAmount(v float32) {
	o.Amount = &v
}

// GetCurrency returns the Currency field value if set, zero value otherwise.
func (o *WebBudgetResponse) GetCurrency() string {
	if o == nil || IsNil(o.Currency) {
		var ret string
		return ret
	}
	return *o.Currency
}

// GetCurrencyOk returns a tuple with the Currency field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *WebBudgetResponse) GetCurrencyOk() (*string, bool) {
	if o == nil || IsNil(o.Currency) {
		return nil, false
	}
	return o.Currency, true
}

// HasCurrency returns a boolean if a field has been set.
func (o *WebBudgetResponse) HasCurrency() bool {
	if o != nil && !IsNil(o.Currency) {
		return true
	}

	return false
}

// SetCurrency gets a reference to the given string and assigns it to the Currency field.
func (o *WebBudgetResponse) SetCurrency(v string) {
	o.Currency = &v
}

// GetHasBudget returns the HasBudget field value if set, zero value otherwise.
func (o *WebBudgetResponse) GetHasBudget() bool {
	if o == nil || IsNil(o.HasBudget) {
		var ret bool
		return ret
	}
	return *o.HasBudget
}

// GetHasBudgetOk returns a tuple with the HasBudget field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *WebBudgetResponse) GetHasBudgetOk() (*bool, bool) {
	if o == nil || IsNil(o.HasBudget) {
		return nil, false
	}
	return o.HasBudget, true
}

// HasHasBudget returns a boolean if a field has been set.
func (o *WebBudgetResponse) HasHasBudget() bool {
	if o != nil && !IsNil(o.HasBudget) {
		return true
	}

	return false
}

// SetHasBudget gets a reference to the given bool and assigns it to the HasBudget field.
func (o *WebBudgetResponse) SetHasBudget(v bool) {
	o.HasBudget = &v
}

// GetMonth returns the Month field value if set, zero value otherwise.
func (o *WebBudgetResponse) GetMonth() string {
	if o == nil || IsNil(o.Month) {
		var ret string
		return ret
	}
	return *o.Month
}

// GetMonthOk returns a tuple with the Month field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *WebBudgetResponse) GetMonthOk() (*string, bool) {
	if o == nil || IsNil(o.Month) {
		return nil, false
	}
	return o.Month, true
}

// HasMonth returns a boolean if a field has been set.
func (o *WebBudgetResponse) HasMonth() bool {
	if o != nil && !IsNil(o.Month) {
		return true
	}

	return false
}

// SetMonth gets a reference to the given string and assigns it to the Month field.
func (o *WebBudgetResponse) SetMonth(v string) {
	o.Month = &v
}

// GetPct returns the Pct field value if set, zero value otherwise.
func (o *WebBudgetResponse) GetPct() int32 {
	if o == nil || IsNil(o.Pct) {
		var ret int32
		return ret
	}
	return *o.Pct
}

// GetPctOk returns a tuple with the Pct field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *WebBudgetResponse) GetPctOk() (*int32, bool) {
	if o == nil || IsNil(o.Pct) {
		return nil, false
	}
	return o.Pct, true
}

// HasPct returns a boolean if a field has been set.
func (o *WebBudgetResponse) HasPct() bool {
	if o != nil && !IsNil(o.Pct) {
		return true
	}

	return false
}

// SetPct gets a reference to the given int32 and assigns it to the Pct field.
func (o *WebBudgetResponse) SetPct(v int32) {
	o.Pct = &v
}

// GetSpent returns the Spent field value if set, zero value otherwise.
func (o *WebBudgetResponse) GetSpent() float32 {
	if o == nil || IsNil(o.Spent) {
		var ret float32
		return ret
	}
	return *o.Spent
}

// GetSpentOk returns a tuple with the Spent field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *WebBudgetResponse) GetSpentOk() (*float32, bool) {
	if o == nil || IsNil(o.Spent) {
		return nil, false
	}
	return o.Spent, true
}

// HasSpent returns a boolean if a field has been set.
func (o *WebBudgetResponse) HasSpent() bool {
	if o != nil && !IsNil(o.Spent) {
		return true
	}

	return false
}

// SetSpent gets a reference to the given float32 and assigns it to the Spent field.
func (o *WebBudgetResponse) SetSpent(v float32) {
	o.Spent = &v
}

func (o WebBudgetResponse) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o WebBudgetResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Amount) {
		toSerialize["amount"] = o.Amount
	}
	if !IsNil(o.Currency) {
		toSerialize["currency"] = o.Currency
	}
	if !IsNil(o.HasBudget) {
		toSerialize["hasBudget"] = o.HasBudget
	}
	if !IsNil(o.Month) {
		toSerialize["month"] = o.Month
	}
	if !IsNil(o.Pct) {
		toSerialize["pct"] = o.Pct
	}
	if !IsNil(o.Spent) {
		toSerialize["spent"] = o.Spent
	}
	return toSerialize, nil
}

type NullableWebBudgetResponse struct {
	value *WebBudgetResponse
	isSet bool
}

func (v NullableWebBudgetResponse) Get() *WebBudgetResponse {
	return v.value
}

func (v *NullableWebBudgetResponse) Set(val *WebBudgetResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableWebBudgetResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableWebBudgetResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableWebBudgetResponse(val *WebBudgetResponse) *NullableWebBudgetResponse {
	return &NullableWebBudgetResponse{value: val, isSet: true}
}

func (v NullableWebBudgetResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableWebBudgetResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
