/*
Pago API

Personal finance tracking API. All /api/_* endpoints require either a session cookie (browser) or an Authorization: Bearer <token> header (machine clients).

API version: 1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package pago

import (
	"encoding/json"
)

// checks if the WebCategoryEntry type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &WebCategoryEntry{}

// WebCategoryEntry struct for WebCategoryEntry
type WebCategoryEntry struct {
	Amount   *float32 `json:"amount,omitempty"`
	Category *string  `json:"category,omitempty"`
	Count    *int32   `json:"count,omitempty"`
	Pct      *float32 `json:"pct,omitempty"`
}

// NewWebCategoryEntry instantiates a new WebCategoryEntry object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewWebCategoryEntry() *WebCategoryEntry {
	this := WebCategoryEntry{}
	return &this
}

// NewWebCategoryEntryWithDefaults instantiates a new WebCategoryEntry object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewWebCategoryEntryWithDefaults() *WebCategoryEntry {
	this := WebCategoryEntry{}
	return &this
}

// GetAmount returns the Amount field value if set, zero value otherwise.
func (o *WebCategoryEntry) GetAmount() float32 {
	if o == nil || IsNil(o.Amount) {
		var ret float32
		return ret
	}
	return *o.Amount
}

// GetAmountOk returns a tuple with the Amount field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *WebCategoryEntry) GetAmountOk() (*float32, bool) {
	if o == nil || IsNil(o.Amount) {
		return nil, false
	}
	return o.Amount, true
}

// HasAmount returns a boolean if a field has been set.
func (o *WebCategoryEntry) HasAmount() bool {
	if o != nil && !IsNil(o.Amount) {
		return true
	}

	return false
}

// SetAmount gets a reference to the given float32 and assigns it to the Amount field.
func (o *WebCategoryEntry) SetAmount(v float32) {
	o.Amount = &v
}

// GetCategory returns the Category field value if set, zero value otherwise.
func (o *WebCategoryEntry) GetCategory() string {
	if o == nil || IsNil(o.Category) {
		var ret string
		return ret
	}
	return *o.Category
}

// GetCategoryOk returns a tuple with the Category field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *WebCategoryEntry) GetCategoryOk() (*string, bool) {
	if o == nil || IsNil(o.Category) {
		return nil, false
	}
	return o.Category, true
}

// HasCategory returns a boolean if a field has been set.
func (o *WebCategoryEntry) HasCategory() bool {
	if o != nil && !IsNil(o.Category) {
		return true
	}

	return false
}

// SetCategory gets a reference to the given string and assigns it to the Category field.
func (o *WebCategoryEntry) SetCategory(v string) {
	o.Category = &v
}

// GetCount returns the Count field value if set, zero value otherwise.
func (o *WebCategoryEntry) GetCount() int32 {
	if o == nil || IsNil(o.Count) {
		var ret int32
		return ret
	}
	return *o.Count
}

// GetCountOk returns a tuple with the Count field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *WebCategoryEntry) GetCountOk() (*int32, bool) {
	if o == nil || IsNil(o.Count) {
		return nil, false
	}
	return o.Count, true
}

// HasCount returns a boolean if a field has been set.
func (o *WebCategoryEntry) HasCount() bool {
	if o != nil && !IsNil(o.Count) {
		return true
	}

	return false
}

// SetCount gets a reference to the given int32 and assigns it to the Count field.
func (o *WebCategoryEntry) SetCount(v int32) {
	o.Count = &v
}

// GetPct returns the Pct field value if set, zero value otherwise.
func (o *WebCategoryEntry) GetPct() float32 {
	if o == nil || IsNil(o.Pct) {
		var ret float32
		return ret
	}
	return *o.Pct
}

// GetPctOk returns a tuple with the Pct field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *WebCategoryEntry) GetPctOk() (*float32, bool) {
	if o == nil || IsNil(o.Pct) {
		return nil, false
	}
	return o.Pct, true
}

// HasPct returns a boolean if a field has been set.
func (o *WebCategoryEntry) HasPct() bool {
	if o != nil && !IsNil(o.Pct) {
		return true
	}

	return false
}

// SetPct gets a reference to the given float32 and assigns it to the Pct field.
func (o *WebCategoryEntry) SetPct(v float32) {
	o.Pct = &v
}

func (o WebCategoryEntry) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o WebCategoryEntry) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Amount) {
		toSerialize["amount"] = o.Amount
	}
	if !IsNil(o.Category) {
		toSerialize["category"] = o.Category
	}
	if !IsNil(o.Count) {
		toSerialize["count"] = o.Count
	}
	if !IsNil(o.Pct) {
		toSerialize["pct"] = o.Pct
	}
	return toSerialize, nil
}

type NullableWebCategoryEntry struct {
	value *WebCategoryEntry
	isSet bool
}

func (v NullableWebCategoryEntry) Get() *WebCategoryEntry {
	return v.value
}

func (v *NullableWebCategoryEntry) Set(val *WebCategoryEntry) {
	v.value = val
	v.isSet = true
}

func (v NullableWebCategoryEntry) IsSet() bool {
	return v.isSet
}

func (v *NullableWebCategoryEntry) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableWebCategoryEntry(val *WebCategoryEntry) *NullableWebCategoryEntry {
	return &NullableWebCategoryEntry{value: val, isSet: true}
}

func (v NullableWebCategoryEntry) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableWebCategoryEntry) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
