/*
Pago API

Personal finance tracking API. All /api/_* endpoints require either a session cookie (browser) or an Authorization: Bearer <token> header (machine clients).

API version: 1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package pago

import (
	"encoding/json"
)

// checks if the WebCategoryBreakdown type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &WebCategoryBreakdown{}

// WebCategoryBreakdown struct for WebCategoryBreakdown
type WebCategoryBreakdown struct {
	Expense []WebCategoryEntry `json:"Expense,omitempty"`
	Income  []WebCategoryEntry `json:"Income,omitempty"`
}

// NewWebCategoryBreakdown instantiates a new WebCategoryBreakdown object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewWebCategoryBreakdown() *WebCategoryBreakdown {
	this := WebCategoryBreakdown{}
	return &this
}

// NewWebCategoryBreakdownWithDefaults instantiates a new WebCategoryBreakdown object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewWebCategoryBreakdownWithDefaults() *WebCategoryBreakdown {
	this := WebCategoryBreakdown{}
	return &this
}

// GetExpense returns the Expense field value if set, zero value otherwise.
func (o *WebCategoryBreakdown) GetExpense() []WebCategoryEntry {
	if o == nil || IsNil(o.Expense) {
		var ret []WebCategoryEntry
		return ret
	}
	return o.Expense
}

// GetExpenseOk returns a tuple with the Expense field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *WebCategoryBreakdown) GetExpenseOk() ([]WebCategoryEntry, bool) {
	if o == nil || IsNil(o.Expense) {
		return nil, false
	}
	return o.Expense, true
}

// HasExpense returns a boolean if a field has been set.
func (o *WebCategoryBreakdown) HasExpense() bool {
	if o != nil && !IsNil(o.Expense) {
		return true
	}

	return false
}

// SetExpense gets a reference to the given []WebCategoryEntry and assigns it to the Expense field.
func (o *WebCategoryBreakdown) SetExpense(v []WebCategoryEntry) {
	o.Expense = v
}

// GetIncome returns the Income field value if set, zero value otherwise.
func (o *WebCategoryBreakdown) GetIncome() []WebCategoryEntry {
	if o == nil || IsNil(o.Income) {
		var ret []WebCategoryEntry
		return ret
	}
	return o.Income
}

// GetIncomeOk returns a tuple with the Income field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *WebCategoryBreakdown) GetIncomeOk() ([]WebCategoryEntry, bool) {
	if o == nil || IsNil(o.Income) {
		return nil, false
	}
	return o.Income, true
}

// HasIncome returns a boolean if a field has been set.
func (o *WebCategoryBreakdown) HasIncome() bool {
	if o != nil && !IsNil(o.Income) {
		return true
	}

	return false
}

// SetIncome gets a reference to the given []WebCategoryEntry and assigns it to the Income field.
func (o *WebCategoryBreakdown) SetIncome(v []WebCategoryEntry) {
	o.Income = v
}

func (o WebCategoryBreakdown) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o WebCategoryBreakdown) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Expense) {
		toSerialize["Expense"] = o.Expense
	}
	if !IsNil(o.Income) {
		toSerialize["Income"] = o.Income
	}
	return toSerialize, nil
}

type NullableWebCategoryBreakdown struct {
	value *WebCategoryBreakdown
	isSet bool
}

func (v NullableWebCategoryBreakdown) Get() *WebCategoryBreakdown {
	return v.value
}

func (v *NullableWebCategoryBreakdown) Set(val *WebCategoryBreakdown) {
	v.value = val
	v.isSet = true
}

func (v NullableWebCategoryBreakdown) IsSet() bool {
	return v.isSet
}

func (v *NullableWebCategoryBreakdown) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableWebCategoryBreakdown(val *WebCategoryBreakdown) *NullableWebCategoryBreakdown {
	return &NullableWebCategoryBreakdown{value: val, isSet: true}
}

func (v NullableWebCategoryBreakdown) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableWebCategoryBreakdown) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
