# coding: utf-8

# flake8: noqa
"""
    Pago API

    Personal finance tracking API. All /api/* endpoints require either a session cookie (browser) or an Authorization: Bearer <token> header (machine clients).

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


# import models into model package
from pago_sdk.models.web_budget_response import WebBudgetResponse
from pago_sdk.models.web_budget_upsert_request import WebBudgetUpsertRequest
from pago_sdk.models.web_categories_response import WebCategoriesResponse
from pago_sdk.models.web_category_breakdown import WebCategoryBreakdown
from pago_sdk.models.web_category_entry import WebCategoryEntry
from pago_sdk.models.web_clone_transaction_request import WebCloneTransactionRequest
from pago_sdk.models.web_create_transaction_request import WebCreateTransactionRequest
from pago_sdk.models.web_delete_transaction_request import WebDeleteTransactionRequest
from pago_sdk.models.web_edit_transaction_request import WebEditTransactionRequest
from pago_sdk.models.web_error_response import WebErrorResponse
from pago_sdk.models.web_message_response import WebMessageResponse
from pago_sdk.models.web_month_point import WebMonthPoint
from pago_sdk.models.web_monthly_analytics_response import WebMonthlyAnalyticsResponse
from pago_sdk.models.web_search_transactions_request import WebSearchTransactionsRequest
from pago_sdk.models.web_search_transactions_response import WebSearchTransactionsResponse
from pago_sdk.models.web_stats_response import WebStatsResponse
from pago_sdk.models.web_transaction_dto import WebTransactionDTO
from pago_sdk.models.web_transactions_response import WebTransactionsResponse
from pago_sdk.models.web_trend_response import WebTrendResponse
from pago_sdk.models.web_year_analytics_response import WebYearAnalyticsResponse
from pago_sdk.models.web_year_month_entry import WebYearMonthEntry
