# coding: utf-8

"""
    Pago API

    Personal finance tracking API. All /api/* endpoints require either a session cookie (browser) or an Authorization: Bearer <token> header (machine clients).

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field
from typing import Any, ClassVar, Dict, List, Optional
from pago_sdk.models.web_category_entry import WebCategoryEntry
from typing import Optional, Set
from typing_extensions import Self

class WebCategoryBreakdown(BaseModel):
    """
    WebCategoryBreakdown
    """ # noqa: E501
    expense: Optional[List[WebCategoryEntry]] = Field(default=None, alias="Expense")
    income: Optional[List[WebCategoryEntry]] = Field(default=None, alias="Income")
    __properties: ClassVar[List[str]] = ["Expense", "Income"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of WebCategoryBreakdown from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in expense (list)
        _items = []
        if self.expense:
            for _item_expense in self.expense:
                if _item_expense:
                    _items.append(_item_expense.to_dict())
            _dict['Expense'] = _items
        # override the default output from pydantic by calling `to_dict()` of each item in income (list)
        _items = []
        if self.income:
            for _item_income in self.income:
                if _item_income:
                    _items.append(_item_income.to_dict())
            _dict['Income'] = _items
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of WebCategoryBreakdown from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "Expense": [WebCategoryEntry.from_dict(_item) for _item in obj["Expense"]] if obj.get("Expense") is not None else None,
            "Income": [WebCategoryEntry.from_dict(_item) for _item in obj["Income"]] if obj.get("Income") is not None else None
        })
        return _obj


